### ISSUE TITLE
Add schema rule for required string values to have a minLength specified

### ISSUE THREAD

**Issue by JonJLee2001** [Redocly/redocly-cli#1011]
I would be beneficial to have a rule that checks that a minLength attribute is applied to all required string properties. Currently if a minLength is not supplied then an empty string is a valid value, which is not what is not the generally understood desired behaviour for required fields (i.e. required should mean "is present and has a value" not just "is present").

**Comment by tatomyr** [comment]
Hi @JonJLee2001,
 Does this custom rule fit your case?
```yaml
rules: 
  assert/minLength-for-required-strings:
    subject: 
      type: Schema

    assertions: 
      mutuallyRequired: 
        - required
        - minLength

    where: 
      - subject: 
          type: Schema
          property: type
        assertions:  
          const: string
     
```

**Comment by JonJLee2001** [comment]
@tatomyr Thank you for your suggestion - however when I run this rule it isn't quite right. It is asserting that every string field must be required and have a minLength, whereas what I need is to only assert on strings that are set to required. I guess I would need to more the required assertion from the assertions section the to where section?

**Comment by tatomyr** [comment]
@JonJLee2001,
Not quite. It rather says that whenever a string property has the `required` field defined, it must also have `minLength` and vice versa. And I see it's not entirely your case.

In theory, the following should have been covering what's needed:

```yaml

rules: 
  assert/minLength-for-required-strings:
    subject: 
      type: Schema

    assertions: 
      required: [minLength]

    where: 
      - subject: 
          type: Schema
          property: type
        assertions:  
          const: string

      - subject: 
          type: Schema
          property: required
        assertions:
          const: true
        
```

Unfortunately, there's a limitation in assertions - you cannot use the same subject type twice in the `where` section. You may check out the [documentation](https://redocly.com/docs/cli/rules/custom-rules/#custom-rules-and-assertions) to find if any other combination could serve you better. But there are also other cases when the `required` field lies outside the `properties` field or a string defined as an `enum`, i. e.:
```yaml

           schema:
              type: object
              properties:
                a:
                  type: string
                b:
                  type: string
                  enum:
                    - x
                    - y
                    - z
              required:
                - b
```

So it looks like it's better to have a separate rule, indeed.

**Comment by adamaltman** [comment]
The example can be abbreviated.

```yaml
 schema:
    type: object
    properties:
      a:
        type: string
      b:
        type: string
    required:
      - b
```

The only way to know that `b` is required when you evaluate the schema is with a custom function.

We should update the custom function example in the docs to show how to do this use case. Why? The custom function examples in the docs are all doable with the `pattern` assertion anyway. So they wouldn't be practical reasons to write a custom function. This is a decent practical reason.

If I understand, the desired behavior is this will throw a problem "Required schema property "b" doesn't have a `minLength` property defined."

```yaml
 schema:
    type: object
    properties:
      a:
        type: string
      b:
        type: string
    required:
      - b
```

This would pass (no problem):

```yaml
 schema:
    type: object
    properties:
      a:
        type: string
      b:
        type: string
        minLength: 1
    required:
      - b
```

Do I misunderstand?
