### ISSUE TITLE
Remove unused components in bundle removes array item references

### ISSUE THREAD

**Issue by onavratil-monetplus** [Redocly/redocly-cli#1012]
Any scheme used via
```
type: array
items:
  $ref: some-reference
```
will be removed if `--remove-unused-components` flag is used in the `redocly bundle` command. 
Same spec with workaround
```
type: array
items:
  allOf:
    -$ref: some-reference
```
will not suffer from this issue.
