### ISSUE TITLE
theme.openapi.schemaDefinitionsTagName configuration not working

### ISSUE THREAD

**Issue by bookofjames** [Redocly/redocly-cli#1015]
**Describe the bug**
**schemaDefinitionsTagName** in theme.openapi may have worked at one time but does not seem to work anymore.

**To Reproduce**
1. check out new version of openapi-starter and run `npm install`
2. edit redocly.yaml to include the following (last line added)
```
theme.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python
  schemaDefinitionsTagName: Schemas
```
3. Run command `npx @redocly/cli preview-docs ./openapi/openapi.yaml`
4. **Schemas** does not show up as a menu item on the left

**Expected behavior**
"Schemas" should show up as a menu item on the left as a tag that groups all schemas together

**OpenAPI definition**
3.1.0

**Redocly Version(s)**
1.0.0-beta.123

**`Node.js` Version(s)**
v14.18.1

**Comment by SmoliyY** [comment]
Hi @bookofjames!
In the `1.0.0-beta.121` release we [changed structure](https://redocly.com/docs/cli/changelog/#100-beta121-2023-01-25) of the config file for the `features` property.
Try this:
```yaml
theme: 
  openapi:
    htmlTemplate: ./docs/index.html
    schemaDefinitionsTagName: Schemas
    theme: 
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:  
        - lang: curl
        - lang: Node.js
        - lang: JavaScript
        - lang: PHP
        - lang: Python
```

**Comment by bookofjames** [comment]
hi @SmoliyY ,

Thanks for the reply.
I copied exactly from your suggestion, but it still does not work.

my full .redocly.yaml:
```
organization: test

extends:
  - minimal

theme: 
  openapi:
    htmlTemplate: ./docs/index.html
    schemaDefinitionsTagName: Schemas
    theme: 
      colors:
        primary:
          main: "#32329f"
    generateCodeSamples:
      languages:  
        - lang: curl
        - lang: Node.js
        - lang: JavaScript
        - lang: PHP
        - lang: Python
```

after this I executed the command `npx @redocly/cli preview-docs openapi/openapi.yaml`

see screenshot -> there is no "Schemas" tag in the left navigation bar.

![Screenshot 2023-02-28 at 9 18 59 AM](https://user-images.githubusercontent.com/26037773/221728225-99a51610-37cc-46ae-b7fe-43197412e377.png)
