### ISSUE TITLE
'.redocly.lint-ignore' does not suppress errors with the `push` comand

### ISSUE THREAD

**Issue by SmoliyY** [Redocly/redocly-cli#1024]
**Describe the bug**

Generated `.redocly.lint-ignore.yaml` does not meet the suppressed errors after push command in the `Api Registry`

**To Reproduce**
1. Given this `redocly.yaml` file 
```yaml
extends:
  - minimal
rules:
  operation-operationId: off
  no-empty-servers: off
  operation-summary: off
  security-defined: off
  no-unresolved-refs: off
  assert/must-provide-mandatory-properties#object-description:
    where:
      - subject:
          type: Schema
          property: type
        assertions:
          enum:
            - object
    subject:
      type: Schema
      property: description
    assertions:
      nonEmpty: true
    message: Object description must be set.
    severity: error
```
3. And this OpenAPI file(s)

openapi.yaml

```yaml 
openapi: 3.0.0
info:
  title: test
  description: some
  version: "1"

paths: {}

components:
  schemas:
    Foo:
      type: object
      properties:
        businessPartner:
          $ref: https://gist.githubusercontent.com/nalesnichok/97351d9860f85170e7df28a89e9f2481/raw/644b2be5caf63ca569ad1aaf849f3e45bb6b273f/petstore.yaml#/components/schemas/Order 
    Bar:
      $ref: bar-ref.yaml
```

bar-ref.yaml

```yaml
type: object
```

4. Run lint command with `--generate-ignore-file`. 

Generated ignore file should be smth like this

.redocly.lint-ignore.yaml

```yaml
openapi.yaml:
  must-provide-mandatory-properties#object-description assertion:
    - '#/components/schemas/Foo/description'
  no-unused-components:
    - '#/components/schemas/Foo'
https://gist.githubusercontent.com/nalesnichok/97351d9860f85170e7df28a89e9f2481/raw/644b2be5caf63ca569ad1aaf849f3e45bb6b273f/petstore.yaml:
  must-provide-mandatory-properties#object-description assertion:
    - '#/components/schemas/Order/description'
bar-ref.yaml:
  must-provide-mandatory-properties#object-description assertion:
    - '#/description'

```
5. Run push command.
6. Check Errors on the API Registry
<img width="1161" alt="Screenshot 2023-03-14 at 13 22 29" src="https://user-images.githubusercontent.com/52038205/224986176-36320d90-0d62-49ca-97b4-d8aac10b6fb3.png">

**Expected behavior**
Errors should be suppressed and ignored.

**Redocly Version(s)**
v1.0.0-beta.124

**Additional context**

Before the `push` command we made `bundle` of the definition and after that previously generated `.redocly.lint-ignore.yaml` is no more valid for bundled definition.
