### ISSUE TITLE
Add a ruleset of "None"

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1033]
**Is your feature request related to a problem? Please describe.**

When I am focused on one particular rule or feature, I want to disable all other rules, and selectively enable the items of interest.

This would be easier if it was possible to lint with no ruleset and then add individual rules to that.

**Describe the solution you'd like**

Additional ruleset that can be chosen, but that does not contain rules. This will mostly be useful for testing.

**Describe alternatives you've considered**

Keep the current setup, but publish a list of what is in the minimal ruleset so that users can turn it all off.

**Additional context**

**Comment by jeremyfiel** [comment]
i've done with with the following config: 

```yaml
rules:
  custom-id/parameters-namedBooleans:
    severity: warn
    suppliedSuffixes:
      - Indicator
plugins:
  - './plugins/index.js'
```
