### ISSUE TITLE
Extends another config with plugins do not add attributes

### ISSUE THREAD

**Issue by lbrun25** [Redocly/redocly-cli#1049]
**Describe the bug**
Extends a plugin does not work.

**To Reproduce**
The entry point config file:
```yaml
extends:
  - recommended
  - ./serverUrls.yml
apis:
  auth@v1:
    root: ./doc/openapi/auth/openapi.yml
`````
 
The child config file `serverUrls.yml` in `plugins/plugin.js`:
`````yaml
apis:
  auth@v1:
    decorators:
      plugin/replace-servers-url:
        serverUrl: https://
plugins:
  - "./plugins/plugin.js"
`````

The `plugin.js` in `plugins`:
````js
const ReplaceServersURL = require('./decorators/replace-servers-url');
const id = 'plugin';

/** @type {import('@redocly/cli').DecoratorsConfig} */
const decorators = {
  oas3: {
    'replace-servers-url': ReplaceServersURL,
  },
};

module.exports = {
  id,
  decorators,
};
`````

**Expected behavior**
The main config should have the same decorators as defined in `serverUrls.yml`.

**Redocly Version(s)**
1.0.0-beta.125

**`Node.js` Version(s)**
v16.15.1

**Comment by tatomyr** [comment]
Hi @lbrun25,

Redocly CLI doesn't extend anything from the nested `apis` section. 

However, you can solve your case either by explicitly specifying the decorator in the `auth@v1` section in the entry file or by moving `decorators` from `apis` to the root level in **serverUrls.yml**:

```yaml
plugins:
  - "./plugins/plugin.js"
decorators:
      plugin/replace-servers-url:
        serverUrl: https://
```
