### ISSUE TITLE
Invalid options are silently ignored

### ISSUE THREAD

**Issue by bojanz** [Redocly/redocly-cli#1065]
This is more of an experience report than a bug report, since it highlights multiple problems while trying to update my config to the latest version.

Updated to v1.0.0-beta.125 and decided to replace `redoc-cli build` with `openapi build-docs `.

The old invocation used a number of CLI options:
```
redoc-cli build openapispec.json -t template.hbs\
- --title "API Documentation"\
- --options.requiredPropsFirst=true\
- --options.hideDownloadButton=true\
- --options.theme.spacing.sectionVertical='8'\
- --options.theme.breakpoints.small='50rem'\
- --options.theme.breakpoints.medium='85rem'\
- --options.theme.breakpoints.large='105rem'\
- --options.theme.typography.fontSize='16px'\
- --options.theme.typography.lineHeight='1.75'\
- --options.theme.typography.fontFamily='Overpass,Arial,OpenSans,sans-serif'\
- --options.theme.typography.headings.fontFamily='Moderat,Overpass,Arial,OpenSans,sans-serif'\
- --options.theme.typography.headings.fontWeight='700'\
- --options.theme.typography.code.fontFamily='Moderat Mono,Courier New,monospace'\
- --options.theme.menu.width='300px'\
- --options.theme.menu.backgroundColor='#fafafa'\
- --options.theme.menu.groupItems.textTransform='none'\
- --options.theme.menu.level1Items.textTransform='none'\
- --options.theme.rightPanel.backgroundColor='#263238'\
- --options.theme.rightPanel.width='40%'
```
Replaced just the command name and got an error about --options no longer existing. Opened the [command docs](https://redocly.com/docs/cli/commands/build-docs/). Can't figure out what should be in --templateOptions (no examples given) and what should be in --theme.openapi.

Tried:
```
openapi build-docs openapispec.json -t template.hbs\
 --title "API Documentation"\
 --templateOptions.requiredPropsFirst=true\
 --templateOptions.hideDownloadButton=true\
 --theme.openapi.spacing.sectionVertical='8'\
 --theme.openapi.breakpoints.small='50rem'\
 --theme.openapi.breakpoints.medium='85rem'\
 --theme.openapi.breakpoints.large='105rem'\
 --theme.openapi.typography.fontSize='16px'\
 --theme.openapi.typography.lineHeight='1.75'\
 --theme.openapi.typography.fontFamily='Overpass,Arial,OpenSans,sans-serif'\
 --theme.openapi.typography.headings.fontFamily='Moderat,Overpass,Arial,OpenSans,sans-serif'\
 --theme.openapi.typography.headings.fontWeight='700'\
 --theme.openapi.typography.code.fontFamily='Moderat Mono,Courier New,monospace'\
 --theme.openapi.menu.width='300px'\
 --theme.openapi.menu.backgroundColor='#fafafa'\
 --theme.openapi.menu.groupItems.textTransform='none'\
 --theme.openapi.menu.level1Items.textTransform='none'\
 --theme.openapi.rightPanel.backgroundColor='#263238'\
 --theme.openapi.rightPanel.width='40%'
```
Looking at the output, it seems that a number of my settings were ignored. Tried to falsify them by introducing a misspelling in each one, and got no error.  I would expect any unknown option to give me an error.

Realized this might not be the way redocly-cli wants to be used nowadays, and I had a `.redocly.yaml` file already, so decided to move my options there. Referencing https://redocly.com/docs/api-reference-docs/configuration/functionality/ I added the following section:
```
features:
  openapi:
    hideDownloadButton: true
    requiredPropsFirst: true
    theme:
      breakpoints:
        small: "50rem"
        medium: "85rem"
        large: "105rem"
      rightPanel:
        backgroundColor: "#263238"
        width: "40%"
      sidebar:
        backgroundColor: "#fafafa"
        width: "300px"
        groupItems:
          textTransform: "none"
        level1Items:
          textTransform: "none"
      spacing:
        sectionVertical: 8
      typography:
        fontFamily: "Overpass,Arial,OpenSans,sans-serif"
        fontSize: "16px"
        lineHeight: "1.75em"
        code:
          fontFamily: "Moderat Mono,Courier New,monospace"
        headings:
          fontFamily: "Moderat,Overpass,Arial,OpenSans,sans-serif"
```
only for the theme options to be ignored again. I tried different structures (features.openapi.theme => theme.openapi as used [here](https://redocly.com/docs/cli/configuration/)) but no change and no error.

So, I am suggesting two things:
- For the CLI to start throwing errors when given unknown command options or configuration objects.
- A docs page extended to demonstrate specifying theme options in the .redocly.yaml
