### ISSUE TITLE
`build-docs` doesn't seem to apply `remove-x-internal`

### ISSUE THREAD

**Issue by emarcotte** [Redocly/redocly-cli#1078]
**Describe the bug**

When I preview docs the `remove-x-internal` decorator works great. When I use `build-docs` it doesn't seem to happen.

**To Reproduce**

Config file:

```
apis:
  public@v1:
    root: ./index.yaml
    decorators:
      remove-x-internal: on
      remove-unused-components: on

  private@v1:
    root: ./index.yaml
```

Run:

```
❯ npx redocly build-docs -o public.html public@v1
Found redocly.yaml and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: public.html (27 KiB) [⏱ 27ms].

❯ npx redocly build-docs -o private.html private@v1
Found redocly.yaml and using theme.openapi options
Prerendering docs
🎉 bundled successfully in: private.html (27 KiB) [⏱ 26ms].

❯ diff public.html private.html
# no output
```

However when running:

```
❯ npx redocly preview-docs public@v1 --port 7777
```
I do not see the private things. If I run

```
❯ npx redocly preview-docs private@v1 --port 7777
```

I do see private.

**Expected behavior**

Internal things are removed from the private.html but remain in public.html.

**OpenAPI definition**

This happens for a larger example I have, but this minimal example fires too.

```
openapi: 3.1.0
info:
  description: hi

paths:
  /something:
    x-internal: true
    get:
      request:
      response:
```

**Redocly Version(s)**

```
"@redocly/cli": "^1.0.0-beta.125"
```

**`Node.js` Version(s)**

```
❯ node --version
v18.12.1
```
