### ISSUE TITLE
Invalid ruleId for assertions problems

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#1096]
**Describe the bug**
The assertion problems have weird ruleId, it should match the id from the config file.

**To Reproduce**

```yaml
assert/info-description:
  subject:
    type: Info
    property: description
  assertions:
    defined: true
    minLength: 30
    pattern: /(\.|\.\n)$/
```

The problem is reported with ruleId `info-description assertion`.

**Expected behavior**
It should be `assert/info-description`

**Additional context**
There is unneeded complexity in the scorecard code because of this.
