### ISSUE TITLE
Running `build-docs` outside project dir fails with `no such file or directory`

### ISSUE THREAD

**Issue by pn-santos** [Redocly/redocly-cli#1186]
**Describe the bug**

I'm not 100% this is a bug or a mis-configuration on my part (or if it's due to the project mount not being done at `/spec`) but as far as I can tell, when I try to `build-docs` from outside the "root" of the project dir  the `redocly/cli` docker image it fails with:
```
Error: ENOENT: no such file or directory '(...)/openapi.yaml'
```

`lint` seems to work fine though.

**To Reproduce**

Given the following dir layout (`/current/dir` is only a placeholder):
```
/current/dir
    ├── src
    │    ├── spec
    │    ├── index.hbs
    │    ├── openapi.yaml
    │    └── redocly.yaml
    └── docs
```
From `/current/dir` running the following command:
```
redocly build-docs src/openapi.yaml --config src/redocly.yaml -o docs/index.html
```
results in the error:
```
Found src/redocly.yaml and using theme.openapi options
Error: ENOENT: no such file or directory '/current/dir/src/src/openapi.yaml'
```
**Note 1**:`src` seems duplicated but not sure where from... my guess is the logic is incorrectly building the path? `src` is not specified anywhere in the configs except as the arg to `build-docs`

My `redocly.yaml` is:
```yaml
extends:
  - recommended

telemetry: off

rules:
  info-license: off

theme:

  openapi:
    hideSchemaTitles: true
    hideDownloadButton: true
    sortTagsAlphabetically: true

    htmlTemplate: index.hbs
```

If I cd into `src` and run:
```
redocly build-docs openapi.yaml --config redocly.yaml  -o ../docs/index.html
```
it works.

I also tried providing the full path for both `openapi.yaml` and `redocly.yaml` but then I ran into the issue of how to specify the path to `index.hbs` from within `redocly.yaml` 

**Expected behavior**

Being able to run the `redocly build-docs` command from anywhere by specifying the path to the `api` and `config` (and I think what would make the most sense - have the `htmlTemplate` path be relative to the config file location).

**Logs**

n/a

**Redocly Version(s)**

`redocly/cli:v1.0.0-rc.3` (docker image)
