### ISSUE TITLE
Sidebarlinks option not working 

### ISSUE THREAD

**Issue by mdymel** [Redocly/redocly-cli#1189]
I'm using redocly/cli v1.0.0-rc.3. 

I've added `sidebarLinks` into my redocly.yaml file and it doesn't work. No links are added in the sidebar when running preview-docs command. 

Here is my config file: 
```
extends:
  - recommended

apis:
  myApi@v1:
    root: ./swagger.json
    rules:
      no-ambiguous-paths: error

theme:
  openapi:
    sidebarLinks:
      beforeInfo:
        - label: "Docs portal home"
          link: "../"
        - label: "Introduction"
          link: "../introduction"
    schemaExpansionLevel: 2
    generateCodeSamples:
      languages:
        - lang: curl
    hideHostname: true
    expandResponses: "200"
    expandDefaultResponse: true
    theme:
      logo:
        gutter: "30px"
      sidebar:
        backgroundColor: "#0f172a"
        textColor: "#fff"
```
