### ISSUE TITLE
Join command creates x-tagGroups that don't match extension schema and fails linting

### ISSUE THREAD

**Issue by johnrengelman** [Redocly/redocly-cli#1203]
**Describe the bug**

When using the `join` command with automatic `x-tagGroup` generation, the cli populates a `description` property on the object using the description from the api that was joined https://github.com/Redocly/redocly-cli/blob/f7a6a036ec8dba9f0b526504d9ad3cd4550f0572/packages/cli/src/commands/join.ts#L324-L343

The resulting document fails when evaluated with the `lint` command, because `description` is not a valid property for `x-tagGroups` elements https://github.com/Redocly/redocly-cli/blob/f7a6a036ec8dba9f0b526504d9ad3cd4550f0572/packages/core/src/types/oas3.ts#L35-L41

**To Reproduce**

1. `npx @redocly/cli join <api1.yml> <api2.yml> -o joined.yml`
2. `npx @redocly/cli lint joined.yml`

**Expected behavior**

**Logs**

```
[1] bundle.yml:5742:5 at #/x-tagGroups/0/description

Property `description` is not expected here.

5740 |     .....<snip>

Error was generated by the spec rule.
```

**OpenAPI definition**

`.redocly.yml` -
```
extends:
  - recommended
rules:
  no-invalid-media-type-examples:
    severity: error
    allowAdditionalProperties: true
  operation-operationId-unique: warn
```

**Redocly Version(s)**

1.0.0

`v16.16.0`
