### ISSUE TITLE
Allow specific lints to be ignored globally

### ISSUE THREAD

**Issue by phil-6** [Redocly/redocly-cli#1224]
**Many of my JSON definitions are used elsewhere and are required to declare a `"$schema"` value. It would be useful to be able add this to be ignored in each file that is checked.**

### Current Auto-Generated `lint-ignore.yaml`
``` yaml
# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
schemas/users/update_request.json:
  spec:
    - '#/$schema'
schemas/users/account_response.422.json:
  spec:
    - '#/$schema'
schemas/users/create_request.json:
  spec:
    - '#/$schema'
schemas/users/account_response.201.json:
  spec:
    - '#/$schema'
schemas/users/sign_in/create_request.json:
  spec:
    - '#/$schema'
```

### Ideal `lint-ignore.yaml`
``` yaml
# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
spec:
  - '#/$schema'
```

### Example JSON

``` json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string",
          "example": "Phil"
        },
        "last_name": {
          "type": "string",
          "example": "Reynolds"
        },
        "email": {
          "type": "string",
          "example": "email@example.com",
          "format": "email"
        },
        "picture": {
          "type": "string",
          "example": "(binary_data)"
        },
        "password": {
          "type": "string",
          "example": "test1234"
        },
        "password_confirmation": {
          "type": "string",
          "example": "test1234"
        }
      },
      "required": [
        "first_name",
        "last_name",
        "email",
        "password",
        "password_confirmation"
      ],
      "additionalProperties": false
    }
  },
  "required": [ "user" ],
  "additionalProperties": false
}
```

referenced via
```json
{
  "post": {
    "security": [],
    "summary": "Create a new user account",
    "description": "",
    "operationId": "userAccountCreate",
    "requestBody": {
      "content": {
        "application/json": {
          "schema": {
            "$ref": "create_request.json"
          }
        }
      }
    },
    "responses": {
      "201": {
        "description": "User created successfully",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "account_response.201.json"
            }
          }
        }
      },
      "422": {
        "description": "Unprocessable Entity",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "account_response.422.json"
            }
          }
        }
      }
    }
  }
}
```
which itself is referenced as a paths variable.

**Comment by tatomyr** [comment]
Hi @phil-6, 

The **lint-ignore** file is supposed to be autogenerated and fine-grained. Thus I'm not sure we will change the current syntax. 

However, I can suggest you a few ways to solve your case. I assume you use OAS 3.0, so you want the `$schema` field to be ignored. First you can use type extension (see [similar issue](https://github.com/Redocly/redocly-cli/issues/689#issuecomment-1129983743)), or alternatively, you can remove this field before linting using [preprocessors](https://redocly.com/docs/cli/resources/custom-plugins/). 

Please let me know if that fits your needs.

**Comment by phil-6** [comment]
> The lint-ignore file is supposed to be autogenerated and fine-grained. 

Ahh, that makes sense.

The type-extension with custom plugin from #689 worked perfectly. Thank you @tatomyr.

---

For anyone in the future who finds this issue, I created a `.redocly.yaml` config file, as I didn't have one already with
``` yaml
plugins:
  - 'schemas/redocly_plugins/redocly-schema.js'
extends:
  - recommended
```

and then my plugin file was:

``` js
module.exports = {
    id: 'redocly-schema',
    typeExtension: {
        oas3(types) {
            // modify types here
            return {
                ...types,
                Schema: {
                    ...types.Schema,
                    properties: {
                        ...types.Schema.properties,
                        $schema: { type: 'string' }
                    }
                }
            };
        },
    }
};

```
