### ISSUE TITLE
New rule: request-contains-parameter

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#1254]
**Is your feature request related to a problem? Please describe.**

We need a built-in rule similar to `response-contains-header` but for checking request parameters: `request-contains-parameter`

It can't be done with configurable rules properly as parameters may exists on multiple levels: `Path`-level params and `Operation`-levle params so we probably need a separate rule for this case.

**Describe the solution you'd like**

```yaml
rules:
  request-contains-parameter:
    severity: error
    parameters:
      get:
        - name: X-REQUEST-ID
          in: header
      post:
        - name: X-REQUEST-ID
          in: header
        - name: X-CSRF-TOKEN
          in: header
```

**Describe alternatives you've considered**

Maybe some different shapes of the parameters config?

**Additional context**

See related rule issue: https://github.com/Redocly/redocly-cli/issues/1253
