### ISSUE TITLE
Configurable rules -- notPattern is not working as expected

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#1280]
I'm trying to negate a pattern in the configurable rules and it's not working as expected

I've used the original rule example for inspiration but we have some exceptions to filter out 

if a response of 200 or 201 includes a schema reference, it should point to the `./schemas` folder but we have one exception where we have a common schema accepted. 

I've tried using a negative look ahead pattern and it appears to work correctly when checked with regexr.com but it's not catching in redocly.  which regex engine is used and is this my error or something with the tooling? 

```yaml
openapi: 3.0.3
info:
  title: blah
  version: 1.1.0
paths:
  /test/api:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../../common/shared/confirm-message-schema_v03.json'
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: './schemas/test-schema_v01.json'
```

```yaml
  rule/mediatype-schema-ref-pattern:
    subject:
      type: MediaType
      property: schema
    where: 
      - subject:
          type: Response
          filterInParentKeys:
            - '200'
            - '201'
        assertions:
          defined: true
      - subject:
          type: MediaType
          property: schema
        assertions:
          ref: /(?!^((\.*\/)+)?common\/shared\/confirm-message-schema_v0[1-3].json$)/
    message: Ref needs to point to "schemas" directory
    assertions:
      ref: /^\.\/schemas\/.*\.json$/
```

I'm not expecting an error for POST 201 but it's failing.

**Comment by jeremyfiel** [comment]
I tried this variation and it seems to be passing the POST 201 correctly now, but it's not filtering out the `notPattern` refs.

```yaml
  rule/mediatype-schema-ref-pattern:
    severity: error
    message: Ref needs to point to "schemas" directory
    subject:
      type: MediaType
      property: schema
    where: 
      - subject:
          type: Response
          filterInParentKeys:
            - '200'
            - '201'
        assertions:
          defined: true
      - subject: 
          type: MediaType
          property: schema
        assertions: 
          ref: true
          notPattern: /^((\.*\/)+)?common\/shared\/confirm-message-schema_v0[1-3].json$/
    assertions:
      ref: /^\.\/schemas\/.*\.json$/
```
```yaml
openapi: 3.0.3
info:
  title: blah
  version: 1.1.0
paths:
  /test/api:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '../../../common/shared/confirm-message-schema_v03.json'
    post:
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: './schemas/test-schema_v01.json'
```

```bash
validating C:/Users/fieljere/downloads/rule-error.yml...
..\..\downloads\rule-error.yml:
  13:17  error    rule/mediatype-schema-ref-pattern  Ref needs to point to "schemas" directory
```

**Comment by RomanHotsiy** [comment]
@jeremyfiel `notPattern` is not supposed to work with $ref. Those are separate assertions.

I believe the problem with your initial approach is that your regexp still matches the string (empty subset of the string).

Try this (I was not able to test it, so please try):

```yaml
  rule/mediatype-schema-ref-pattern:
    subject:
      type: MediaType
      property: schema
    where: 
      - subject:
          type: Response
          filterInParentKeys:
            - '200'
            - '201'
        assertions:
          defined: true
      - subject:
          type: MediaType
          property: schema
        assertions:
          ref: /^(?!((\.*\/)+)?common\/shared\/confirm-message-schema_v0[1-3].json$)/
    message: Ref needs to point to "schemas" directory
    assertions:
      ref: /^\.\/schemas\/.*\.json$/
```

The difference is very tiny. I moved `^` out of the negative lookahead.

I think we should have support for negative regexp for $ref somehow too for convenience.
