### ISSUE TITLE
Generate all build-docs at once from config.yaml

### ISSUE THREAD

**Issue by matejsp** [Redocly/redocly-cli#1294]
**Describe the problem to be solved**
Based on the configuration you can specify multiple open api specs and run linter on all of them by default.
https://redocly.com/docs/cli/configuration/#example-redocly-configuration-file
However when I run it for build-docs it output just the first api.

**Describe the solution you'd like**
I would like it to support the same style as it is for lint for build-docs:
```
redocly build-docs --config=./config.yaml
```
Basically it should loop across all apis and generate docs for all of them.
It should be noted that output parameter should be added to the config.

**Describe alternatives you've considered**
First we tryed running specs it in for loop with detecting file names using jq command. But it was very slow since we have 140 yamls and it takes 5 minutes to run them all (creating new redoc process each time).
Second try was to run them in parallel and it was a lot faster.

**Additional context**
```
apis:
  account_activity@v1:
    root: ./folder/account_activity.yaml
    output: ./folder/account_activity.yaml
    theme:
      openapi:
        downloadDefinitionUrl: account_activity.yaml
  account@v1:
    root: ./account.yaml
    output: ./account.html
    theme:
      openapi:
        downloadDefinitionUrl: account.yaml
  api_v2@v1:
    root: ./api_v2/api_v2.yaml
    output: ./api_v2/api_v2.html
    theme:
      openapi:
        downloadDefinitionUrl: api_v2.yaml
```
