### ISSUE TITLE
Configurable Rules - Mandatory Title, Fields Order, Schema Nesting

### ISSUE THREAD

**Issue by kekel87** [Redocly/redocly-cli#1298]
Hello,

We've been using redoc-cli since it became available in beta, and it's truly a fantastic tool!

We're currently in the process of cleaning up our API documentation and breaking it down into files, as shown in examples [link1](https://redocly.com/docs/resources/multi-file-definitions/) and [link2](https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/).

To improve the quality of our documentation, we've set some rules as recommendations, including custom rules. However, we're facing challenges with a few of them. Do you have any ideas on these issues?

1. Making Titles Mandatory in Schema Files:
We tried following the documentation, but it seems that requiring titles makes them mandatory everywhere. Our intention is for titles to be mandatory at the root level of the file (not within sub-properties). For example:

```yaml
# component/schema/schema-name.yaml
title: TitleRequiredHere # Required title
type: object
properties:
  aProperties:
    # Not required here
    type: object
```

2. Enforcing a Specific Order for Fields:
Here, our goal is to standardize and make the documentation more readable by specifying an order for properties. Something like this:

```yaml
# paths/path-name.yaml
get:
  summary:
  description:
  operationId:
  tags:
  parameters:
  security: []
  responses:
```

A rule like:

```yaml
rule/path-prop-order
  subject:
    type: Paths
  assertions:
    order: [summary, description, operationId, tags, parameters, security, responses]
```

3. Avoiding Nesting of Objects and Enums:
We encourage our teams to break down schemas for reusability.

```yaml
# component/schema/schema-name.yaml
title: Title
type: object
properties:
  aProperties:
    type: object # Trigger error, to make a dedicated file with a ref
    properties:
      aSubProperties:
        type: integer
  aEnumProperties:
    type: string
    enum:  # Trigger error, to make a dedicated file with a ref
      - value1
      - value1
```

Any guidance on these issues would be greatly appreciated.
However, it seems like the linter doesn't work well with split files, particularly regarding node type resolution. For instance:

**Comment by tatomyr** [comment]
Thanks for your kind words @kekel87! Let me check your examples.

**Comment by tatomyr** [comment]
Regarding your first case, you may try using the `ref` assertion:

```yaml
rules:
  rule/case-1:
    subject: 
      type: Schema
      property: title
    assertions: 
      defined: true
    where: 
      - subject: 
          type: Schema
        assertions:  
          ref: true
```

It will also trigger on internal refs, so you might want to play a bit further with that rule.


The second example is a good case for using a [custom function](https://redocly.com/docs/cli/rules/configurable-rules/#custom-function-example). You may implement something similar to [sortOrder assertion](https://github.com/Redocly/redocly-cli/blob/bdf0e7d8c2fc39e9714f2c0fb95083c74fde06c0/packages/core/src/rules/common/assertions/asserts.ts#L256-L281).

**Comment by tatomyr** [comment]
Next to your 3rd example. First of all, you can transitively reference your schemas inside other schemas:
```yaml
$ref: ./component/schema/schema-name.yaml#/properties/aProperties
```


So you can leverage reusability without extracting the sub-schemas. 
However, if you still want, this combination of rules should do the trick:

```yaml
  rule/case-3-object:
    subject: 
      type: Schema
      property: type
    assertions: 
      notPattern: /^object$/
    where: 
      - subject: 
          type: SchemaProperties
        assertions: 
          defined: true
    
  rule/case-3-enum:
    subject: 
      type: Schema
      property: enum
    assertions: 
      defined: false
    where: 
      - subject: 
          type: SchemaProperties
        assertions: 
          defined: true

```

**Comment by tatomyr** [comment]
And you probably forgot to attach an example of a wrong lint behaviour on split files 🙂.

**Comment by kekel87** [comment]
Great, thank you very much for the quick responses!

- The first rule works very well! I didn't fully grasp how 'where' works, though.
- I'll attempt to write the second rule later today. `sortOrder` isn't mentioned in the site's [documentation](https://redocly.com/docs/cli/rules/configurable-rules/#assertion-object). Thanks for the example.
- The last rules aren't working because it flags schemas with `type: object` defined at the root of the "schema" files (likely because they are imported with `$ref`, maybe). I'm wondering if there's something to be done similar to the first rule, using 'where' + 'assertion: ref.' The enum isn't working either; I'm trying to figure out why.

To provide a bit more context on the last rule, ultimately, we aim to:
- generate code with openapi-generator
- detect and clean up all schema duplications
So, encouraging our developers to structure and name things appropriately should result in much cleaner code and make it easier to identify duplicates.

I don't have specific examples for the linter, but I think I've understood. It bundles the files to verify the rules, right?

**Comment by kekel87** [comment]
Just for sharing, here are our current rules in case it might be of interest to others:
```yaml
extends:
  # https://redocly.com/docs/cli/rules/#recommended-config
  - recommended
rules:
  # See https://redocly.com/docs/cli/rules/
  no-unused-components: error
  paths-kebab-case: error
  rule/no-vendor-extensions:
    severity: warn
    subject:
      type: any
    message: To respect the OpenAPI standard, please do not use vendor extensions
    assertions:
      notPattern: /^x-/
  rule/operation-operationId-camel-case:
    severity: error
    subject:
      type: Operation
      property: operationId
    assertions:
      defined: true
      casing: camelCase
    message: Operation operationId must be defined and in camelCase.
  rule/components-title-pascal-case:
    subject:
      type: Components
      property: title
    assertions:
      casing: PascalCase
    message: Schema title must be in PascalCase.
  rule/schema-title-defined:
    subject:
      type: Schema
      property: title
    assertions:
      defined: true
    where:
      - subject:
          type: Schema
        assertions:
          ref: true
    message: Schema title must be defined.
  # TODO rule/path-order
  # TODO rule/avoid-nested-object
  # TODO rule/avoid-nested-enum
```

**Comment by kekel87** [comment]
Okay, I think I've succeeded in my assertion to check the order.

I did something quick and ignored all the extra keys, but it works.

Thanks again for the example! :heart: 

```yaml
plugins:
  - 'plugin.js'
rules:
  rule/path-order:
    subject:
      type: PathItem
      property:
        - get
        - post
        - put
        - delete
    assertions:
      local/order:
        order:
          - summary
          - description
          - operationId
          - tags
          - parameters
          - security
          - responses
```

<details>
<summary>plugin.js</summary>


```js
module.exports = {
  id: 'internal',
  assertions: {
    order: (
      value, options, context
    ) => {
      const order = options.order || options;

      if (!Array.isArray(order) || order.length > 1) {
        return [
          {
            message: `"order" should be an array with multiple entries.`,
            location: context.baseLocation,
          },
        ];
      }

      if (!Array.isArray(value) && typeof value !== "object") {
        return [];
      }

      let toTest = Array.isArray(value) ? [...value] : Object.keys(value);

      // Remove un-ordered value
      toTest = toTest.filter((v) => order.includes(v));

      if (toTest.length < 2) {
        return [];
      }

      // Remove extra order value
      const cleanOrder = order.filter((v) => toTest.includes(v));

      // Test order
      if (JSON.stringify(cleanOrder) === JSON.stringify(toTest)) return [];

      return [
        {
          message: `Must follow this order:\n  Expected: ${cleanOrder.join(',')}\n  Provided: ${toTest.join(',')}`,
          location: context.baseLocation,
        },
      ];
    },
  },
};
```

</details>

<details>
<summary>Output on error</summary>

```
rule/path-order failed because the PathItem get, post, put, delete didn't meet the assertions: Must follow this order:
  Expected: summary,description,operationId,tags,parameters,security,responses
  Provided: summary,tags,responses,operationId,description,security,parameters
```

</details>

**Comment by jeremyfiel** [comment]
> Just for sharing, here are our current rules in case it might be of interest to others:

Please consider contributing to the public configurable rules repo.  https://github.com/Redocly/redocly-cli-cookbook

**Comment by kekel87** [comment]
Okay, I think I've found a solution. I had to create two rules each time, one for `properties` and one for `array` (I may have forgotten specific cases).

It would have been simpler to only allow "type: object" and "enum" at the root of a file, but I don't see how to achieve that (in the sense that a "root of a file" doesn't exist for the linter).

So here are the rules for **nested objects**:
```yaml
  rule/no-nested-object-properties:
    subject:
      type: Schema
      property: type
    assertions:
      notPattern: /^object$/
    message: To ensure better splitting and naming, reduce duplication, please put this object in a dedicated file.
    where:
      - subject:
          type: SchemaProperties
          filterInParentKeys:
            - properties
        assertions:
          defined: true
      - subject:
          type: Schema
        assertions:
          ref: false

  rule/no-nested-object-array:
    subject:
      type: Schema
      property: type
    assertions:
      notPattern: /^object$/
    message: To ensure better splitting and naming, reduce duplication, please put this object in a dedicated file.
    where:
      - subject:
          type: Schema
          filterInParentKeys:
            - items
        assertions:
          defined: true
          ref: false
```

Example:

```yaml
# components/schemas/my-title.yaml
title: MyTitle
type: object # ✅ good
properties:
  one:
    type: object  # ❌ error
  two:
    type: array
    items:
      type: object  # ❌ error
```

And for **nested enums**:

```yaml
  rule/no-nested-enum-properties:
    subject:
      type: Schema
      property: enum
    assertions:
      defined: false
    message: To ensure better splitting and naming, reduce duplication, please put this enum in a dedicated file.
    where:
      - subject:
          type: SchemaProperties
          filterInParentKeys:
            - properties
        assertions:
          defined: true
      - subject:
          type: Schema
        assertions:
          ref: false

  rule/no-nested-enum-array:
    subject:
      type: Schema
      property: enum
    assertions:
      defined: false
    message: To ensure better splitting and naming, reduce duplication, please put this enum in a dedicated file.
    where:
      - subject:
          type: Schema
          filterInParentKeys:
            - items
        assertions:
          defined: true
          ref: false
```

Example:

```yaml
# components/schema/enums/my-enum.yaml
title: MyEnum
type: string
enum: # ✅ good
  - value

# components/schemas/my-title.yaml
title: MyTitle
type: object
properties:
  one:
    type: string
    enum: # ❌ error
      - value
  four:
    type: array
    items:
      type: string
      enum:  # ❌ error
        - value
```

Thanks for your help. 🙏

I'll try to find some time to contribute to the cookbook. 😅
