### ISSUE TITLE
Configurable rules: can't target named schema in subject

### ISSUE THREAD

**Issue by samanthawritescode** [Redocly/redocly-cli#1301]
**Motivation**
I'm ultimately to write a configurable rule to check that all `SchemaProperties` are in kebab-case _with some exceptions._ I thought that I could do this by using some combination of `where` and `filterInParentKeys`, but I'm running into unexpected issues. I'm not sure if it's a bug or my misunderstanding.

Here's a pared down version of my schema, defined under `components.schemas` as a named schema:
```yaml
MySchema:
  type: object
  properties:
    id:
      type: string
    badKeyA:
      type: object
      properties:
        valid-key-a:
          type: object
          properties:
            valid-key-b:
              type: string
            headers:
              type: object
              properties:
                Accept:
                  type: string
                User-Agent:
                  type: string
            badKeyC:
              type: string
        badKeyB:
          type: string
          format: date-time
```

I'd like to write a rule to validate that every schema property in my entire spec is in kebab-case _except_ anything under `headers` for _this specific schema only_.

**Attempts and Issues**

So, to start, this "works", in the sense that it doesn't return a validation error for the `Accept` or `User-Agent` properties and it does return one for all the `badKey`s. 

```yaml
  rule/my-schema-kebab-case:
    where:
      - subject:
          type: Schema
          filterOutParentKeys:
            - headers
        assertions:
          defined: true
    subject:
      type: SchemaProperties
    assertions:
      casing: kebab-case
```

However, what if I have `header` keys in other schemas that I _do_ want to validate case within? So, I attempted to write a rule that targeted only `MySchema`: 

```yaml
  rule/my-schema-kebab-case:
    where:
      - subject:
          type: Schema
          filterInParentKeys:
            - MySchema
        assertions:
          defined: true
    subject:
      type: SchemaProperties
    assertions:
      casing: kebab-case
```

This, inexplicably to me, does not work. Running `lint` says my schema is valid. However, running `lint` with this rule (changing `MySchema` to `badKey`), tells me that `badKeyB` is invalid:

```yaml
  rule/my-schema-kebab-case:
    where:
      - subject:
          type: Schema
          filterInParentKeys:
            - badKey
        assertions:
          defined: true
    subject:
      type: SchemaProperties
    assertions:
      casing: kebab-case
```

**Expected behavior**

Since the node type for `MySchema` and `badKey` are both `Schema`, I would expect targeting `MySchema` as a parent key to work similar to how I can target `badKey`. In the case where I filter by the parent key `MySchema`, I would expect the output of `lint` to at least tell me that `badKey` is invalid.

**OpenAPI version**
3.1.0

**Redocly Version(s)**
1.2.0

**`Node.js` Version(s)**
v16.15.1

**Additional Notes**
I tried to keep this mostly focused on the one problem of not being able to target `MySchema` as a parent key, but I would **greatly** appreciate any general help on writing the rule(s) that I ultimately want!
