### ISSUE TITLE
missing items sibling 'items' for Schemas with 'type: array', not being reported.

### ISSUE THREAD

**Issue by pranayinos** [Redocly/redocly-cli#1318]
When I run the lint on my OpenAPI definition document, the tool does not reports missing items in type: array inside request and response body.  

**To Reproduce**

1. Given this `spec_defn` file **openapi_3.0.txt** attached here -> [openapi_3.0.txt](https://github.com/Redocly/redocly-cli/files/13265733/openapi_3.0.txt)
3. Run this command with these arguments... `redocly lint main.yaml`
4. **missing items field in ids array should be reported**, but validation succeeds with message "Woohoo! Your API description is valid. 🎉"

**Expected behavior**

Missing items if any should be reportes as per OAS 3.0 specs.

"items MUST be present if the type is array" in following docs below:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md

**Logs**

NA

**OpenAPI description**

"items MUST be present if the type is array" in following docs below:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md
**Redocly Version(s)**

1.4.0

**`Node.js` Version(s)**
NA

**Comment by jeremyfiel** [comment]
This validation is an omission by the OAS specification when they wrote the JSON Schema for OAS 3.0.x. 

The OAS Schema object does not have a `required` array of properties for each type of `type`. The schema is unconstrained. 

[OAS Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/schemas/v3.0/schema.json#L335)  You may want to file an issue in the [OAS github](https://www.github.com/OAI/OpenAPI-Specification/issues)

**Comment by tatomyr** [comment]
Hi @pranayinos,
If you want to enforce this particular behaviour you can use a [configurable rule](https://redocly.com/docs/cli/rules/configurable-rules/) like this:

```yaml
rules:
  rule/siblings:
    subject: 
      type: Schema
    assertions:
      required:
        - items    
    where:
      - subject:
          type: Schema
          property: type
        assertions: 
          const: array
    message: The 'items' field is required for schemas of array type.
    
```
