### ISSUE TITLE
Configurable rule doesn't evaluate as expected

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#1320]
**Describe the bug**

My configurable rule doesn't seem to evaluate correctly 

**To Reproduce**

`redocly lint --config redocly.yaml <file> --format stylish`

```yaml
rules:
  rule/post-should-define-requestBody:
      severity: error
      message: '"POST" SHOULD define a "requestBody" schema unless using an "actions" pattern'
      subject:
        type: Operation
      where:
        - subject:
            type: Paths
          assertions:
            notPattern: /.*actions.*/
        - subject:
            type: Operation
            filterInParentKeys:
              - post
          assertions:
            defined: true
        - subject:
            type: Operation
            property: deprecated
          assertions:
            defined: false
      assertions:
        required:
          - requestBody
```

**Expected behavior**

I'm expecting two errors in this description

- `/core/v4/protected/search/warmup` with no `requestBody` defined
- `cars/and/coffee` with no `requestBody` defined

**OpenAPI description**

```json
{
    "openapi": "3.0.3",
    "info": {
        "title": "test",
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "https://www.redocly.com"
        }
    ],
    "tags": [
        {
            "name": "Protected / Secure Search",
            "description": "Search warmup to initialize the search user profile and manage entitlements for a given user"
        }
    ],
    "paths": {
        "/core/v4/protected/search/warmup": {
            "post": {
                "description": "Search warmup to initialize the search user profile and manage entitlements for a given user",
                "tags": [
                    "Protected / Secure Search"
                ],
                "summary": "Protected Search User Profile Initialization",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/problem+json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/cars/and/coffee": {
            "post": {
                "description": "Search warmup to intialize the search user profile and manage entitlements for a given user",
                "tags": [
                    "Protected / Secure Search"
                ],
                "summary": "Protected Search User Profile Initialization",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/problem+json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/core/v4/protected/search/actions/{action-id}": {
            "post": {
                "description": "Search warmup to initialize the search user profile and manage entitlements for a given user",
                "tags": [
                    "Protected / Secure Search"
                ],
                "summary": "Protected Search User Profile Initialization",
                "parameters": [
                    {
                        "name": "action-id",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "string"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/problem+json": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

```

**Redocly Version(s)**

1.4.0 

**`Node.js` Version(s)**

v18.15.0

**Additional context**

Not sure if this change is related. I tried installing 1.2.0 and didn't see any change in the output, so I can only assume this didn't regress.  https://github.com/Redocly/redocly-cli/pull/1299

**Comment by tatomyr** [comment]
A few things are going on here. First, if you're targeting `Paths` in the `where` section, the logic applies to all its paths simultaneously. Instead, you have to target a specific path like this:

```yaml
      ...
      where:
        - subject:
            type: PathItem
            matchParentKeys: /actions/
          assertions:
            defined: true

```

Next, you're referencing `Operation` twice. The limitation here is you can use a node type only once in the where. 

I didn't dig deep, but hopefully you'll find this helpful.

**Comment by jeremyfiel** [comment]
i think I fixed it with this regex. 

`/^([\w-\{\}\/.](?<!\/actions))*$`

> ^ starts with
group #1 [\w-/{}.]  any of these characters which captures the entire path string
group #2 (?<!/actions)  negative look behind from the end of the string and negate `/actions`
$ end

**Comment by tatomyr** [comment]
Looks like this is what you were looking for 🙂
Don't you mind contributing to the [cookbook](https://github.com/Redocly/redocly-cli-cookbook)?

**Comment by jeremyfiel** [comment]
final rule looks like this: 

this is meant to throw an error for any uri pattern which has a `post` with no `requestBody`. 

we make exceptions when we use a command pattern in the uri..such as: 

`/api/v1/things/{thing-id}/actions/{action-id}`

which translates to 

`/api/v1/things/123/actions/submit`


```yaml
rules:
  rule/post-should-define-requestBody:
    severity: error
    message: '"POST" SHOULD define a "requestBody" schema unless using an "actions" pattern'
    subject:
      type: Operation
    where:
      - subject:
          type: PathItem
          matchParentKeys: /^([\w-\{\}\/.](?<!\/actions))*$/
        assertions:
          defined: true
      - subject:
          type: Operation
          filterInParentKeys:
            - post
        assertions:
          disallowed:
            - deprecated
    assertions:
      required:
        - requestBody
```
