### ISSUE TITLE
Want to use Japanese for oprationId

### ISSUE THREAD

**Issue by yossydev** [Redocly/redocly-cli#1325]
**Is your feature request related to a problem? Please describe.**

When I write in yaml and use the `operationId` in Japanese, I encounter an error when using the CLI.

**Describe the solution you'd like**

https://redocly.com/docs/cli/rules/operation-operationId-url-safe/
According to the documentation, there is a possibility that it may be treated as a URL by some tools, which I understand.
However, I believe it should be fine to use Japanese if we are not using those tools. Could it be made usable by passing an option??:eyes:

**Describe alternatives you've considered**

Using `operationId` in English: In the project I'm currently involved in, we use Japanese. Therefore, if possible, I would prefer to continue using Japanese.

**Additional context**

Related: https://github.com/drwpow/openapi-typescript/issues/1435

**Comment by adamaltman** [comment]
What error d you encounter?

**Comment by tatomyr** [comment]
@yossydev you can switch off the corresponding rule (either [in the config](https://redocly.com/docs/cli/configuration/rules/#configuring-rules) or with the `--skip-rule` inline option) if you believe it is safe to use that in your API description. However, if you want to enforce the use of Japanese characters, you might want to set up an additional [configurable rule](https://redocly.com/docs/cli/rules/configurable-rules/) using a regex:

```yaml
rules:
  rule/operation-id-japanese:
    subject:
      type: Operation
      property: operationId
    assertions: 
      pattern: <here goes your regex>

```
