### ISSUE TITLE
Properties from merged references are ignored when using `bundle`

### ISSUE THREAD

**Issue by Gidgidonihah** [Redocly/redocly-cli#1329]
When merging references, `redocly-cli bundle` will ignore existing properties.

For example with 2 files:
`id.yaml`:

```yaml
type: integer
format: int32
description: A generic ID used everywhere
example: 42
```

`id_ro.yaml`:

```yaml
$ref: ./id.yaml
readOnly: true
description: A generic ID but that is specifically read only
```

The result will never include `readOnly: true` or the updated description.

**To Reproduce**

I've [created a gist][gist-bug] with a minimal working example and reproduction steps.

1. Given default settings
1. And the `example.yaml` (and referenced files) in the gist
3. Run the bundle command(s) found in the gist
    (e.g. `docker run --rm -v $PWD:/spec redocly/cli bundle example.yaml -o out-redocly-cli.yaml`)
4. See ignored merged properties

**Expected behavior**

The duplicate properties defined *after* reference should appear in the resulting yaml file.

**Logs**

N/A

**OpenAPI description**

See the files supplied in the linked gist.
Only default configuration was used with the supplied yaml files.

**Redocly Version(s)**

`1.4.0` as built in the docker image

**`Node.js` Version(s)**

`v21.1.0` as built in the docker image

**Additional context**

I used the `latest` tagged docker image at the time I ran it. Image hash `3bcfba9186cf`
Additional details and output can be found [in the gist][gist-bug].

[gist-bug]: https://gist.github.com/Gidgidonihah/7c852857fc54677156c1135085a6f1f4

**Comment by tatomyr** [comment]
Hi @Gidgidonihah,
Could you check if using the `allOf` trick solves your issue?  

```yaml
allOf: 
- $ref: ./id.yaml
readOnly: true
description: A generic ID but that is specifically read only
```
