### ISSUE TITLE
Configurable Rules: Strip whitespace and line terminators in multiline yaml strings

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#1353]
**Is your feature request related to a problem? Please describe.**

When using `pattern` assertion, I want to use a multi-line string `|` or `>` because I have quite a large regex with many conditions. I want to format it so it's easier to read. I'm getting an invalid RegEx expression error. I believe it's because the RegExp string contains `\n` or `\r` characters. 

I also tried using the "chomp indicator": `strip` which is equivalent to `>-`
>“Strip” mode: indicated by a - in the block header, this will strip not only trailing empty lines like in clip mode, but also the final newline at the end of the string.

```yaml
rules:
  rule/paths-uri-pattern-must-match:
    severity: error
    message: URI pattern must follow XXXX
    subject:
      type: Paths
    assertions:
      pattern: >-
        '/^\/(
            many|conditional|items|
            |to|conditionally
            |validate)
          \/v[1-9]
          \/[a-z-/\{\}]+
        /'
```

```bash
Syntax error: Invalid regular expression: /'/^\/(/: Unterminated group SyntaxError: Invalid regular expression: /'/^\/(/: Unterminated group
    at new RegExp (<anonymous>)
    at regexFromString (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\rules\common\assertions\utils.js:209:23)
    at Object.pattern (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\rules\common\assertions\asserts.js:42:51)
    at runAssertion (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\rules\common\assertions\utils.js:203:46)
    at applyAssertions (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\rules\common\assertions\utils.js:60:32)
    at C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\rules\common\assertions\utils.js:115:26
    at visitWithContext (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\walk.js:239:13)
    at walkNode (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\walk.js:132:29)
    at walkNode (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\walk.js:187:25)
    at walkDocument (C:\Users\fieljere\AppData\Roaming\npm\node_modules\@redocly\cli\node_modules\@redocly\openapi-core\lib\walk.js:32:5)
```
**Describe the solution you'd like**

Please strip these characters out so I can use my regex. 

**Describe alternatives you've considered**

using a single line makes reading the long regex very difficult

**Additional context**

**Comment by jeremyfiel** [comment]
tangentially, I think I want to target `PathItems` instead of `Paths` here, but I wasn't able to get it to trigger the error.   I tried using the following rule and it didn't work.  Some additional help with this one would be appreciated! 

```yaml
rules:
  rule/paths-uri-pattern-must-match:
    severity: error
    message: URI pattern must follow XXXX
    subject:
      type: PathItem
      matchParentKeys: |
        '/^\/(
            many|conditional|items|
            |to|conditionally
            |validate)
          \/v[1-9]
          \/[a-z-/\{\}]+
        /'
    assertions:
      defined: true
```

**Comment by jeremyfiel** [comment]
it's possible the `DumpOptions` from `stringifyYaml` method in `js-yaml` is the fix to this problem.  

**Not tested**


> * if true flow sequences will be condensed, omitting the space between `key: value` or `a, b`. Eg. `'[a,b]'` or `{a:{b:c}}`.
    * Can be useful when using yaml for pretty URL query params as spaces are %-encoded. (default: false).
     */
    condenseFlow?: boolean | undefined;

**Comment by tatomyr** [comment]
Hi @jeremyfiel!

I think there's something wrong with the formatting. Could you check this instead?

```yaml
rules:
    rule/paths-uri-pattern-must-match:
      severity: error
      message: URI pattern must follow XXXX
      subject:
        type: Paths
      assertions:
        pattern: >-
          /^\/(
          many|conditional|items|
          |to|conditionally
          |validate)
          \/v[1-9]
          \/[a-z-/\{\}]+
          /
```

**Comment by jeremyfiel** [comment]
here's a repro

it's not failing for invalid RegExp expression if I fix the indentation, but it also doesn't validate the pattern correctly


```yaml
openapi: 3.0.3
info:
  title: blah
  version: 1.0.0
servers:
  - url: www.redocly.com
tags: 
  - name: thing
    description: a thing 
paths:
  /core/v1/thing/{thing-id}:
    get:
      summary: a summary
      description: a description
      tags: 
        - thing
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
        "400":
          description: Bad Request
          content:
            application/json:
              schema: {}

```

```yaml
# redocly.yaml
rules:
  rule/paths-uri-pattern-must-match:
    severity: error
    message: URI pattern must follow SFFO
    suggest:
      - "/<domain>/<version>/<feature>/function>/<operation>"
    subject:
      type: Paths
    assertions:
      # Starts with /<domain>/<version>/<feature>
      pattern: >-
        /^\/(core)
        \/v[1-9]
        \/[a-z-/\{\}]+
        /
```
