### ISSUE TITLE
Configurable Rules: need advice on targeting a property

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#1393]
I'm trying to write a rule to guarantee every referenced schema has a `title` property at the root of the schema.  I do not want every property to have a `title` though. 

I tried this rule and it does target the root `title`, but it also targets all sub schemas. This is not the behavior I want. 

```yaml
  rule/schema-must-contain-title:
    severity: warn
    message: Schema MUST contain title
    subject: 
      type: Schema
      property: title
    assertions: 
      defined: true
```

Take this example, no error is thrown for the root of the `LinkType_v01` schema, but I'm seeing two errors for `linkID` and `href` subschemas. 
```json
{
        "$schema": "http://json-schema.org/draft-04/schema#",
        "title": "",
        "allOf": [ { "$ref": "./common/linkType_v01.json" }]
}
```
```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "LinkType_v01",
	"description": "A link description object is used to describe link relations.  In the context of a schema, it defines the link relations of the instances of the schema, and can be parameterized by the instance values.  The link description format can be used on its own in regular (non-schema) documents, and use of this format can be declared by referencing the normative link description schema as the schema for the data structure that uses the links.",
	"type": "object",
	"properties": {
		"linkID": {
			"description": "Simple (string) identifier of an object to be used when there is no appropriate specific named ID Type",
			"type": "string",
			"pattern": "^[a-zA-Z0-9.$-_/]+$"
		},
		"href": {
			"description": "The URI of the related entity, typically used to represent any internet or social network address",
			"type": "string",
			"format": "uri"
		}
	}
}
```

Is there a way to ONLY target the root of a referenced schema?

**Comment by tatomyr** [comment]
I think so. You may look into this issue to get some inspiration: https://github.com/Redocly/redocly-cli/issues/1298. Please let me know if that helps.

**Comment by jeremyfiel** [comment]
the rule for this is shared from #1298. 

```yaml
  rule/schema-ref-must-contain-title:
    severity: warn
    message: Referenced schema MUST contain title
    where:
      - subject: 
          type: Schema
        assertions: 
          ref: true
    subject: 
      type: Schema
      property: title
    assertions: 
      defined: true
```
