### ISSUE TITLE
Exclude Tags Without Endpoints from Left Sidebar in the API documentation

### ISSUE THREAD

**Issue by stiflerGit** [Redocly/redocly-cli#1396]
**Is your feature request related to a problem? Please describe.**
Our team utilizes Redocly to manage our API, employing it to filter out specific endpoints with a given x-audience value for subsequent documentation generation. However, during the filter-out phase, some tags remain unused by any endpoints, yet they are still displayed on the left sidebar of the documentation page.

**Describe the solution you'd like**
I propose the inclusion of an option to exclude tags from the left panel if they are not associated with any endpoints.

**Additional context**
Here is a screenshot of the left side panel containing all the tags.
![image](https://github.com/Redocly/redocly-cli/assets/23660892/7f1b61cf-a933-4c92-9ca3-f0ed291de444)

**Comment by lornajane** [comment]
Thanks for the suggestion! I'd usually recommend that you remove the tags at the same time that you do the filtering, there's [a custom decorator to remove tags](https://github.com/Redocly/redocly-cli-cookbook/tree/main/custom-plugin-decorators/remove-unused-tags) in the cookbook that could be a good fit. If you find it useful, perhaps we should consider promoting it to be a built-in decorator.

**Comment by stiflerGit** [comment]
> Thanks for the suggestion! I'd usually recommend that you remove the tags at the same time that you do the filtering, there's [a custom decorator to remove tags](https://github.com/Redocly/redocly-cli-cookbook/tree/main/custom-plugin-decorators/remove-unused-tags) in the cookbook that could be a good fit. If you find it useful, perhaps we should consider promoting it to be a built-in decorator.

Hi @lornajane, this is exactly what we were looking for—thank you very much. After some adjustments, it worked like a charm. I believe it would be beneficial to include it as an option for the `filter-in` and `filter-out` decorators. Here's an example:
```yml
apis:
    api-subset:
        root: src/my-api.yml
        decorators:
            filter-in:
                property: x-audience
                value:
                    - Subset1
                matchStrategy: any
                no-unused-tags: on
```
