### ISSUE TITLE
[Question] Configurable rule to check any schemas within responses

### ISSUE THREAD

**Issue by samanthawritescode** [Redocly/redocly-cli#1466]
Apologies if there was a better place for this. 

I'm trying to write a rule that **doesn't** allow the `enum` property within API **responses**, but **does** allow it within API **requests**.

Either of these options definitely work if I wanted to disallow the `enum` property everywhere: 
```yaml
rule/no-enums:
  subject:
    type: Schema
    property: enum
  assertions:
    defined: false
```
```yaml
rule/no-enums:
  subject:
    type: any
    property: enum
  assertions:
    defined: false
```

But I'm completely struggling to write something that only targets `Schema` nodes referenced from anything under a `Response` node. Among other things, I've tried: 
```yaml
rule/no-enums-in-responses:
  where:
    - subject:
        type: Response
      assertions:
        defined: true
  subject:
    type: Schema
    property: enum
  assertions:
    defined: false
```
and even enumerating all the nodes between `Response` and a `Schema`: 
```yaml
rule/no-enums-in-responses:
  where:
    - subject:
        type: Response
      assertions:
        defined: true
    - subject:
        type: MediaTypesMap
      assertions:
        defined: true
    - subject:
        type: MediaType
      assertions:
        defined: true
  subject:
    type: Schema
    property: enum
  assertions:
    defined: false
```
I've also tried things like: 
```yaml
rule/no-enums-in-responses:
  where:
    - subject:
        type: Response
        filterInParentKeys:
          - '200'
      assertions:
        defined: true
  subject:
    type: Schema
  assertions:
    disallowed:
      - enum
```

I'm at a loss. I'm even trying to run these on a bundled version of my spec so there are no references to possibly mess things up. Thanks in advance for any help!

**Comment by tatomyr** [comment]
This is interesting. 

Schema could contain other schemas, and, in fact, in your example, you refer to a nested schema. 
If you aren't using the `where` clause, it propagates further down the nested schemas.
The problem here is that whenever you use the `where`, it stops at the first `Schema` level it encounters after `Response` (which, in your case, doesn't contain an enum).

I'm not entirely certain if we want to change the behaviour as it will change how the existing rules work (it might actually be useful for some). I have to think about this more. 

As a workaround, you can write a [custom rule through a plugin](https://redocly.com/docs/cli/custom-plugins/custom-rules/) for that case. However, it requires some knowledge of JavaScript.

A different workaround might be adding another level of the `where` funnel:

```yaml
  rule/no-enums-in-responses:
    where:
      - subject:
          type: Response
        assertions:
          defined: true
      - subject: 
          type: SchemaProperties # <-- this ensures we bypass the first level of Schema and check only on the 2nd level 
        assertions: 
          defined: true
        
    subject:
      type: Schema
    assertions:
      disallowed: 
        -  enum
  ```

Please keep in mind that the rule will only check for enums in the first `Schema` inside of the first `SchemaProperties`. 

Let me know if that helps.
