### ISSUE TITLE
enhance no-http-verbs-in-paths with excludedPaths option

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#1501]
**Is your feature request related to a problem? Please describe.**

https://redocly.com/docs/cli/rules/no-http-verbs-in-paths/

Invariably, there are going to be false positives. Rather than adding them to the Redocly ignore file (which I tend to use more as an API design debt log) I want to be able to list excluded paths as a rule configuration.

**Describe the solution you'd like**

```
rules:
  no-http-verbs-in-paths:
    splitIntoWords: true
    excludedPaths:
      - /foo/profile-options/
```
|Option|Type|Description|
|---|---|---|
|excludedPaths	|[string]|	List of paths to exclude from evaluation by this rule.|

**Describe alternatives you've considered**

Doing nothing and using the Redocly ignore file (but it feels noisy to me).

**Additional context**

n/a
