### ISSUE TITLE
Support better means to set environment variables

### ISSUE THREAD

**Issue by kpervin** [Redocly/redocly-cli#1557]
**Is your feature request related to a problem? Please describe.**

Currently there is only a single way to load environment variables into the config, and that is via the `envVariable` field in the `resolve.http.headers` array. However, you cannot load these into ` apis.{config}.root` or into the `resolve.http.headers[num].matches` field.

**Describe the solution you'd like**

A means of loading env variables [akin to GraphQL Config](https://the-guild.dev/graphql/config/docs/user/schema#environment-variables). They use a library called [`string-env-interpolation`](https://github.com/kamilkisiela/string-env-interpolation) ([ref to line in their source](https://github.com/kamilkisiela/graphql-config/blob/553ea681c1d428212113e9bb8c467f45b12b3cb3/src/helpers/cosmiconfig.ts#L24)).

**Comment by kpervin** [comment]
It would be nice to be able to provide env variables for pretty much the whole config, apart from the reserved key fields. For example:

```yaml
apis:
  v4:
    root: https://${DOMAIN}/v3/api-docs/User%20API%20v4
    x-openapi-ts:
      output: ./src/v4.d.ts
  v3:
    root: https://${DOMAIN}/v3/api-docs/UserV3
    x-openapi-ts:
      output: ./src/v3.d.ts
resolve:
  http:
    headers:
      - matches: https://${DOMAIN}/**
        name: Authorization
        envVariable: ${API_KEY}
```
