### ISSUE TITLE
Ability to exclude some operations from security-defined rule

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#1569]
**Is your feature request related to a problem? Please describe.**

Very often API define a health endpoint which is not protected by any kind of auth.

Our `security-defined` rule always reports this as a problem.

Surely, it can be ignored with ignore file but this is a problem for users who constantly onboard new APIs.
Configurable rule can't be used here as it doesn't cover security defined on different levels (operation vs root).

**Describe the solution you'd like**

Add support for `exceptions` config option to the rule:

```yaml
rules:
  security-defined:
    severity: error
    exceptions:
      - path: '/health'
        method: GET
```

**Describe alternatives you've considered**

I used `exceptions` as we use this term in `path-segment-plural` rule. Let me know if you have better suggestions.

Another alternative is to have a simpler list of exceptions (only path)

```yaml
rules:
  security-defined:
    severity: error
    exceptions:
      - '/health'
```

What do you think?
