### ISSUE TITLE
Document behaviour of lint cli args after `--` 

### ISSUE THREAD

**Issue by collinsauve** [Redocly/redocly-cli#1581]
**Is your feature request related to a problem? Please describe.**

We use [pre-commit](https://pre-commit.com/) to automatically hook up a number of linters to our repository.  

This tool sends the files that are to be commited as extra command-line arguments to redocly.  By way of example, I use a pre-commit config like this:

```
      - id: my-api lint
        name: my-api lint
        entry:
          pnpm --package=@redocly/cli@1.14.0 dlx redocly lint my-api --config .redocly/config.yaml
        files: ^path\/to\/spec\/.*$
        language: system
```

Unfortunately due to the above pre-commit behaviour of sending the changed files, the actual command will be sent like this:

```
pnpm --package=@redocly/cli@1.14.0 dlx redocly lint my-api --config .redocly/config.yaml path/to/spec/file-that-i-changed.yml
```

Redocly interprets that last argument as a *config* file.

I found a work-around wherein if I add a `--` to the end of the command, Redocly lint ignores anything after it!

**Describe the solution you'd like**

Pretty simply: Can you confirm that is indeed the expected and supported behaviour, or am I doing some [spacebar heating](https://xkcd.com/1172/)?  If it is supported, can it be called out in [the docs](https://redocly.com/docs/cli/commands/lint/)? 

**Describe alternatives you've considered**

Possibly could wrap it in my own shell script that throws away args.   

**Additional context**

If the above is not clear, I'd be happy to provide a minimum reproduction by way of a small example repository.
