### ISSUE TITLE
Detect properties with no type defined

### ISSUE THREAD

**Issue by LasneF** [Redocly/redocly-cli#1614]
**Describe the solution you'd like**

given a specification , it would like to ensure that all properties has a given type assidned (after resolution of $ref , and may be combination of allof etc) 

to me most of the time if the properties is not defined is not on purpose but because it has been forgoten . I know that the schema is valid but still looks at least a warning would increase the API quality 

**Describe alternatives you've considered**

create a dedicated rules could be an alternative

**Comment by tatomyr** [comment]
Hi! I wonder if something really simple like the following can help you:

```yaml
rules:
  rule/require-type-in-schemas:
    subject:
      type: Schema
    assertions:
      requireAny:
        - type
        - allOf
        - anyOf
        - oneOf

```

However, in general case, I'd recommend writing a [custom rule](https://redocly.com/docs/cli/custom-plugins/custom-rules) for that.

**Comment by jeremyfiel** [comment]
This rule will work for you. That way you don't need to define every possible JSON Schema keyword 


```yaml
rules:
  rule/require-type-in-schema:
  severity: warn
  message: `type` must be defined
  subject:
   type: Schema
   property: type
  assertions:
    defined: true
```

**Comment by tatomyr** [comment]
@jeremyfiel thanks, it's a good one. However, it will fail to validate cases like this:

```yaml
components:
  schemas:
    Foo:
      allOf:
        - type: object
        - properties: 
            bar: 
              type: string
```

It will require defining types at two more levels, which is excessive:

```yaml
components:
  schemas:
    Foo:
      type: object # <- redundant
      allOf:
        - type: object
        - properties: 
            bar: 
              type: string
          type: object  # <- redundant
```
