### ISSUE TITLE
Using curl instead of the cli interface 

### ISSUE THREAD

**Issue by dan-r95** [Redocly/redocly-cli#1631]
**Is your feature request related to a problem? Please describe.**

I'm trying to use redocly using GitLab  CI/CD pipeline, and do not want to use the npm package as it would bloat my runners.
I tried to use the docker image as a pipeline step, but got intro trouble finding the redocly binary as illustrated below

```
upload_doc:
  image:
    name: ghcr.io/redocly/cli
    entrypoint:   [""]
  stage: post_build
  script:
    - export REDOCLY_TELEMETRY=off
    - export REDOCLY_AUTHORIZATION=$REDOCLY_AUTHORIZATION
    - /usr/local/bin/redocly  lint --extends recommended openapi3.json  || true
    - /usr/local/bin/redocly push  api.yml --destination="destName@v1" --organization "orgName"
  dependencies:
   - build_dev
```

```
/usr/local/bin/redocly: No such file or directory
```
while the binary is in this folder in the container. 

**Describe the solution you'd like**

For the use case like above, using curl / REST api would be totally fine.
I imagine something like
```curl -X PUT  redocly-hostname/tenant/xxx/definitions/defID --header "token XXX" --data {{contentOf-api.yml}}  ```

**Describe alternatives you've considered**

Like mentioned above, I used the docker image unsuccessfully.
