### ISSUE TITLE
Add `boolean-schema-prefixes` (analogue to `boolean-parameter-prefixes`) rule to schema/model validation

### ISSUE THREAD

**Issue by i-terzic** [Redocly/redocly-cli#1632]
**Is your feature request related to a problem? Please describe.**
I've noticed that the rule `boolean-parameter-prefixes` for parameters would also be useful for validating schemas which use booleans.

**Describe the solution you'd like**
Add a rule `boolean-schema-prefixes` (suggestions are more than welcomed) to the built-in rules to be able to enforce the same constraints as provided `boolean-parameter-prefixes`

**Describe alternatives you've considered**
Implementing a rule manually, but i think adding this to the built-in rules will benefit more developers.

**Additional context**

**Comment by tatomyr** [comment]
Hi @i-terzic, would a simple configurable rule like the one below fit your needs?

```yaml
rules:
  rule/boolean-schema-prefixes:
    subject:
      type: Schema
      matchParentKeys: ^(?!is|has).*$
      property: type
    assertions:
      defined: true
      notPattern: ^boolean$
    message: "Boolean property names should contain one of the prefixes: 'is', 'has'."
```

The highlighting is on the boolean type, so it might not be too obvious at first glance what's wrong, but the message could be adjusted to clarify it.
