### ISSUE TITLE
[OAS 3 spec] License object `identifier` and `url` keys are mutually-exclusive

### ISSUE THREAD

**Issue by bradjones1** [Redocly/redocly-cli#1645]
**Describe the bug**

According to [the OAS 3 spec](https://swagger.io/specification/#license-object), `identifier` and `url` are mutually-exclusive in a `license` object. Redocly CLI wrongly asserts that the `url` field is required.

**To Reproduce**

Specify a `name` and `identifier` in a `license` object. Redocly reports

```
License object should contain `url` field.
```

**Expected behavior**

The license object rule actually enforces _either_ `identifier` or `url` (or neither) are present, but not both. It should also assert that `name` is specified, as it is required.

**Logs**

```
License object should contain `url` field.

4 | title: 'Meet Kinksters - JSON API'
5 | version: 'Versioning not (yet) implemented.'
6 | license:
  | ^^^^^^^
7 |   name: 'GNU General Public License v2.0 or later'
8 |   identifier: ' GPL-2.0-or-later'

Warning was generated by the info-license-url rule.
```

**Redocly Version(s)**

`1.18.1`

**Comment by tatomyr** [comment]
Hi @bradjones1, I recommend you switch off the `info-license-url` rule in your **redocly.yaml**. Instead, you can write a [configurable rule](https://redocly.com/docs/cli/rules/configurable-rules) like the one below to ensure that either `url` or `identifier` are present in your `license`:


```yaml
rules:
  info-license-url: off
  rule/info-licence-required-fields:
    subject:
      type: License
    assertions:
      requireAny:
        - url
        - identifier
      mutuallyExclusive:
        - url
        - identifier
```

I hope that helps.
