### ISSUE TITLE
After upgrading v1.19.0->1.20.0: failed to load plugin...please provide a valid path

### ISSUE THREAD

**Issue by el2iot2** [Redocly/redocly-cli#1673]
After upgrading to v1.20.0, the JavaScript plugin that I wrote was no longer found and prevented commands from working:

## Works in v1.19.0 #
```Powershell
> npx @redocly/cli@1.19.0 build-docs myapi -o yada.html

    ╔═══════════════════════════════════════════════════════╗
    ║                                                       ║
    ║  A new version of Redocly CLI (1.20.0) is available.  ║
    ║  Update now: `npm i -g @redocly/cli@latest`.          ║
    ║  Changelog: https://redocly.com/docs/cli/changelog/   ║
    ║                                                       ║
    ╚═══════════════════════════════════════════════════════╝

Found .redocly.yaml and using theme.openapi options
Prerendering docs
Non-existing tag "tenant-provisioning" is added to the group "Administration / Operation"
Non-existing tag "trait-async-event" is added to the group "Traits"
Non-existing tag "trait-relo-distribution" is added to the group "Traits"

🎉 bundled successfully in: yada.html (1787 KiB) [⏱ 3ms].

> npx @redocly/cli@1.19.0 check-config

    ╔═══════════════════════════════════════════════════════╗
    ║                                                       ║
    ║  A new version of Redocly CLI (1.20.0) is available.  ║
    ║  Update now: `npm i -g @redocly/cli@latest`.          ║
    ║  Changelog: https://redocly.com/docs/cli/changelog/   ║
    ║                                                       ║
    ╚═══════════════════════════════════════════════════════╝


Properties 'enumSkipQuotes', 'sortOperationsAlphabetically', 'sortTagsAlphabetically', 'htmlTemplate', 'theme' are only used in API Reference Docs and Redoc version 2.x or earlier.

✅  Your config is valid.
```

## Fails in v1.20.0
```
> npx @redocly/cli@1.20.0 build-docs myapi -o yada.html
Something went wrong when processing :

  - Failed to load plugin "plugins/myplugin.js". Please provide a valid path

> npx @redocly/cli@1.20.0 check-config
Something went wrong when processing :

  - Failed to load plugin "plugins/myplugin.js". Please provide a valid path
```
## OpenAPI description

OpenApi: 3.1

## .redocly.yaml

```yaml
# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  myapi:
    root: yada/openapi/openapi_myapi.yaml
    rules:
      no-server-example.com:
        severity: off
      tag-description:
        severity: off
      paths-kebab-case:
        severity: off
      operation-4xx-response:
        severity: off
      no-invalid-media-type-examples:
        severity: off
        allowAdditionalProperties: true
  #  snip other APIs
plugins:
  - plugins/myplugin.js
extends:
  - recommended
rules:
  no-unused-components:
    severity: warn
  no-invalid-media-type-examples:
    severity: warn
    allowAdditionalProperties: true
theme:
  openapi:
    codeSamples: 
      languages: 
        - lang: C#
        - lang: curl

    enumSkipQuotes: true
    sortOperationsAlphabetically: true
    sortTagsAlphabetically: true
    htmlTemplate: ./docs/index.html
    theme:
      logo:
        gutter: 3em
      rightPanel:
        backgroundColor: 'rgb(0, 91, 119)'

      colors:
        error:
          main: rgb(203, 44, 48)
        accent:
          main: '#ffc845'
        primary:
          main: 'rgb(0, 91, 119)'
```
### plugins/myplugin.js
```javascript
const XAudience = require('./decorators/x-audience.js');
//Other plugins, very similar pattern
const X2 = require('./decorators/x2.js');
const X3 = require('./decorators/x3.js');

module.exports = {
  id: 'myplugin',
  decorators: {
    oas3: {
      'x-audience': XAudience,
      'x-2': X2,
      'x-3': X3
    }
  }
};
```
### plugins/decorators/x-audience.js
```javascript
const utils = require('./utils.js');

module.exports = XAudience;

function XAudience({ value }) {
    console.log("x-audience: " + value);
    let usedTags = {};
    return {
        Root: {
            leave: (node) => {
                utils.DropUnusedTags(node, usedTags);
            }
        },
        Operation: {
            enter: (node, ctx) => {
                let found = node['x-audience'];
                if (found != value) {
                    delete ctx.parent[ctx.key];
                }
                else {
                    utils.MarkTagUsed(node, usedTags);
                }
            }
        },
        PathItem: {
            leave: (node, ctx) => {
                utils.DeletePathItemIfEmpty(node, ctx);
            }
        }
    }
};
```
***

**`Node.js` Version(s)**

```Powershell
> node --version
v20.7.0
```

**Additional context**

Running via NPX.
