### ISSUE TITLE
Files section in redocly.yaml file is ignored and when executing a 'push' command all files from the folder are being pushed

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#1689]
**Describe the bug**

We received a report from a customer stating that when attempting to push an API to the Redocly API Registry using CI/CD, all files in the folder are being pushed instead of just the selected files.

**To Reproduce**

1. Create an API Registry using CI/CD.
2. Create a folder with yaml file, index.html file and other files.

```yml
apis:
  testclipush@v1:
    root: test.yaml

files:
  - index.html
extends: 
  -  minimal
theme:
  openapi:
    htmlTemplate: ./index.html
    hideTryItPanel: false
    theme:
      colors:
        primary:
          main: '#0065FB'
  ```
2. In files select to only upload  index.html 
3. Execute push command 
4. Observe that all files from the folder will be pushed

**Expected behavior**

Only selected files should be pushed

Sample file:
[333.zip](https://github.com/user-attachments/files/16781261/333.zip)
