### ISSUE TITLE
'remove-unused-components' decorator is not working at the per-API level.

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#1695]
**Describe the bug**

When you configure decorator: 'remove-unused-components' per API level it will not remove the unused 
**To Reproduce**

1. Given this `redocly.yaml` file

```yml
apis:
  testclipush@v1:
    root: redint.yaml
    decorators:
      remove-x-internal: on
      remove-unused-components: on


extends: 
  -  minimal


# decorators:
#   remove-unused-components: on
```

2. And this OpenAPI file
[redint.yaml.zip](https://github.com/user-attachments/files/16796310/redint.yaml.zip)

3. Run 'redocly bundle' command
4. Observe that unused component 'StartDate' is not removed from the API definition

**Redocly Version(s)**

1.21.1
