### ISSUE TITLE
New minor 1.23.0 release causes breaking change in bundle output option

### ISSUE THREAD

**Issue by pierrerm** [Redocly/redocly-cli#1715]
**Describe the bug**

Hey team 👋 
The new release 1.23.0 causes a breaking change. It seems like the output folder is now treated as an output file.

**To Reproduce**
We have the following make command to bundle some spec files:
```
npx @redocly/cli bundle ${API_FILES} -o ./generated/
```

As of 1.23.0, it outputs a single file named `generated.yaml` in the `./` folder:
```
.
└── generated.yaml
```

**Expected behavior**

Before, it would output one file per spec file in `API_FILES` to the `./generated/` folder.
```
.
├── generated
    ├── some_spec_file.yaml
    ├── another_spec_file.yaml
    └── ...
```

**Logs**

N/A

**OpenAPI description**

OAS 3.0.0

**Redocly Version(s)**

Just upgraded to 1.23.0. Everything was working fine with 1.22.0.

**Comment by pierrerm** [comment]
We indeed don't have the `output` location specified in our config file, although it used to work without.
So now we need it to be able to bundle multiple spec files? Without it, the example command
```
redocly bundle --output dist --ext json openapi/openapi.yaml openapi/museum.yaml
```
Would yield:
```
dist.json
```

**Comment by tatomyr** [comment]
> But how could I specify this in the config? It seems like I can only have one output location per spec file right?

Example in **redocly.yaml**:

```yaml
apis:
  external:
     root: openapi.yaml
     decorators:
         x-internal: on
     output: generated/openapi.yaml
  internal:
     root: openapi.yaml
     output: generated/internal/openapi.yaml

```
