### ISSUE TITLE
Configurable rules for non-OpenAPI formats

### ISSUE THREAD

**Issue by lornajane** [Redocly/redocly-cli#1718]
**Describe the bug**

I expected to be able to write configurable rules to check my Arazzo descriptions, but the rules don't seem to apply as I expected.

**To Reproduce**

1. Given this `redocly.yaml` file

```
extends: 
  - recommended

arazzoRules:
  sourceDescription-name-unique: warn
  workflowId-unique: warn

rules:
  rule/flow-prefix:
    subject:
      type: Workflow
      property: workflowId
    assertions:
      pattern: /test/

  rule/info-description:
    subject:
      type: Info
      property: description
    assertions:
      defined: true
      minLength: 300

```

3. And this ~~OpenAPI file(s)~~ Arazzo file: https://github.com/Redocly/museum-openapi-example/blob/main/arazzo/museum-api.arazzo.yaml
4. Run this command with these arguments... `redocly lint museum-api.arazzo.yaml`
5. No configurable rules are applied

**Expected behavior**

Lint errors because the API description doesn't meet the rules.

**Redocly Version(s)**

1.23.0

**`Node.js` Version(s)**

20.4.0
