### ISSUE TITLE
Support for 'main stream' format validation  for the no-invalid-schema-examples rules

### ISSUE THREAD

**Issue by LasneF** [Redocly/redocly-cli#1729]
**Is your feature request related to a problem? Please describe.**

given an API specification , i would like that example are validated not only about the type but as well about the format 

for instance  as of today this example is mentionned as valid with the rules no-invalid-schema-examples set

```
        expiry:
          type: string
          format  : date
          example: TN
```

**Describe the solution you'd like**

i would like either a parameter on the no-invalid-schema-examples rule 
either a dedicated rules that would validate example toward format 

notice that the rules should support combination with oneOf  for instance such 

```
        expiry:
          type: string
          oneOf:
            - format: date
            - enum:
                - SPOT
                - TODAY
                - TN
                - 'ON'
                - TOM
          example: TN
```
          should not be spot as an error (as it is currently raised as such)
          

**Describe alternatives you've considered**

no alternative :) 

**Additional context**

it should be done for main stream format like at minimum date and date-time that are the most used 
any support of https://spec.openapis.org/registry/format/ would be a bonus
