### ISSUE TITLE
How to force a parameter to have an example

### ISSUE THREAD

**Issue by andrefpoliveira** [Redocly/redocly-cli#1748]
I would like to confirm that any parameter has an example defined. So, in the example below, it would throw an error in `fromDateTime` but `toDateTime` would be OK.
```
      parameters:
        - name: fromDateTime
          in: query
          required: true
          schema:
            type: string
            format: yyyy-MM-dd HH:mm
        - name: toDateTime
          in: query
          required: true
          schema:
            type: string
            format: yyyy-MM-dd HH:mm
            example: 2024-01-28 11:13
```

Thank you!

**Comment by tatomyr** [comment]
Hi @andrefpoliveira, you can define a configurable rule like this in your **redocly.yaml** file to check each parameter has an example:

```yaml
rules:
  rule/require-example-in-parameters:
    subject:
      type: Parameter
      property: example
    assertions:
      defined: true
```

Or, for your exact case, you can check that every schema inside parameters has an example: 

```yaml
rules:
  rule/require-example-in-parameter-schemas:
    where:
      - subject:
          type: Parameter
        assertions:
          defined: true
    subject:
      type: Schema
      property: example
    assertions:
      defined: true
```

Please let me know if that helps.
