### ISSUE TITLE
split command does not support plugins

### ISSUE THREAD

**Issue by yurym-ping** [Redocly/redocly-cli#1822]
Calling `split` with plugins doesn't invoke them.

```
npx @redocly/cli split ./my-service/openapi.yaml \
    --config ./redocly-split.yaml \
    --outDir=./dist/my-service
```

where `redocly-split.yaml` contains

```
extends:
  - minimal

# apparently split command does not support plugins

preprocessors:
  plugin/root-path-workaround: on

decorators:
  plugin/set-oas-version:
    version: 3.1.0

plugins:
  - plugin.js
```

and `plugin.js` contains:

```
const SetOASVersion = require("./plugins/set-oas-version");
const RootPathWorkaround = require("./plugins/root-path-workaround");

module.exports = {
  id: 'plugin',
  preprocessors: {
    oas3: {
      "set-oas-version": SetOASVersion,
      "root-path-workaround": RootPathWorkaround,
    },
  },
}
```

**Expected behavior**

`./dist/my-service/openapi.yaml` is modified by the plugins.

**Logs**

```
npx @redocly/cli split ./my-service/openapi.yaml \
    --config ./redocly-split.yaml \
    --outDir=./dist/my-service
Deprecated plugin format detected: plugin
🪓 Document: ./my-service/openapi.yaml is successfully split
    and all related files are saved to the directory: ./dist/my-service
```

Specification version: 3.0
Redocly Version: 1.26.0
`Node.js` Version: 20.15.1
OS, environment: macOS
