### ISSUE TITLE
root attribute in config file no longer accept http:// URL since 1.26.1

### ISSUE THREAD

**Issue by lephuongbg** [Redocly/redocly-cli#1836]
**Describe the bug**

**To Reproduce**

1. Given this `redocly.yaml` file
    
    ```yaml
    extends:
      - recommended
    apis:
      admin:
        root: http://api:5000/admin/api/openapi.json
    ```
2. And this OpenAPI file(s)
3. Run this command with these arguments... 
    
    ```
    npx --yes @redocly/cli@1.26.1 bundle --config redocly-cli.yaml --remove-unused-components admin -o src/schemas/admin-api.yaml`
    ```
 

    ```
    http:/api:5000/admin/api/openapi.json does not exist or is invalid.
    
    Please provide a valid path.
    ```

**Expected behavior**

redocly cli should be able to fetch the openapi definition from provided URL

**Logs**

**OpenAPI description**

**Redocly Version(s)**

1.26.1

**`Node.js` Version(s)**

20

**OS, environment**

linux

**Additional context**
