### ISSUE TITLE
Ability to re-configure severity of configurable rules

### ISSUE THREAD

**Issue by collinsauve** [Redocly/redocly-cli#1865]
**Is your feature request related to a problem? Please describe.**

When a configurable rule is defined in another ruleset that is pulled in via `extends`, we would like to have the option to disable (reconfigure the severity) of that rule.  

**Describe the solution you'd like**

For example:

```yaml
# ./default-ruleset.yaml
extends:
  - recommended-strict

rules:
  rule/post-response-status-no-other-2xx:
    subject:
      type: Responses
    where:
      - subject:
          type: Operation
          filterInParentKeys:
            - post
        assertions:
          defined: true
    assertions:
      pattern: ^(20[124]|[345]\d{2}|default)$
      mutuallyExclusive:
        - '201'
        - '202'
        - '204'
    message: Must not define 2xx outside of 201, 202, and 204.
```

```yaml
# config.yaml
extends:
  - ./default-ruleset.yaml
apis:
  # multiple other apis that do *not* disable the rule
  my-api:
    root: ./my-api/openapi.yml
    rules: 
      rule/post-response-status-no-other-2xx: off
```

This currently warns with 

```
Expected type `Assert` (object) but got `string`

149 | rule/post-response-status-no-other-2xx: off

Warning was generated by the configuration spec rule.
```

**Describe alternatives you've considered**

Some alternatives considered:
1. Copy the rule to every other API that does not wish to disable it.  Causes a maintenance burden.
2. Convert to a plugin rule. I'm confident writing these but prefer to use configurable rules when possible as they are easier to maintain.
3. Another feature request to allow `extends` on a per [API object](https://redocly.com/docs/cli/configuration/reference/apis) basis. 

**Additional context**
