### ISSUE TITLE
Merge-resolve per-API with root configuration not fully supported

### ISSUE THREAD

**Issue by mscheerschmidt-mhp** [Redocly/redocly-cli#1871]
**Describe the bug**

Parameters of custom plugins (decorators) are not being merged with parameters from root configuration.

**To Reproduce**

1. Given a `redocly.yaml` file
2. defining a custom decorator
3. which has two options _tag_ and _version_
4. when the root decorator config defines values for both
5. when configuring per-API with version=v2, leaving tag undefined
6. then param **tag remains undefined** in the decorator execution

```
extends:
    - recommended
plugins:
    - plugins/mine.js
decorators:
    mine/add-api-id:
        tag: x-mine-api-id
        version: v1
theme:
    openapi:
        showExtensions: [ x-mine-api-id ]
apis:
    mine@v2:
        root: ./mine_v2.yaml
        decorators:
            mine/add-api-id:
                version: v2
```
and
```
function OperationApiId({tag, version}) {
    console.log(`Decorating with tag ${tag} and version ${version}...`);
}
```
yields: `Decorating with tag undefined and version v2...`

Defining another api element which doesn't mention the plugin makes use of the root configuration.

**Expected behavior**

It should yield: `Decorating with tag x-mine-api-id and version v2...`.

Configured parameters should be merge-resolved just as the docs say:

> If per-API and root settings modify the same properties, per-API settings overrides root settings.

See https://redocly.com/docs/cli/configuration/apis

**Redocly Version(s)**

CLI 1.28.0

**Comment by tatomyr** [comment]
@mscheerschmidt-mhp it's not a bug, rather some misunderstanding. By 'settings' we mean the decorators or rules themselves, not their parameters. For example, if you define a decorator with the same name (but different parameters) on the root and the api levels, the api-level one will override the root one (so only the api-level parameters will be used). I'm not sure how to better clarify that in the docs though. @Redocly/technical-writers could you suggest better wording?

**Comment by mscheerschmidt-mhp** [comment]
Thanks for your quick reply. Would you maybe consider adding this as an enhancement?
The benefit would be that one can define defaults on the root level for decorators etc.
Within per-API definitions one only has to set what needs to be overridden.

**Comment by tatomyr** [comment]
@mscheerschmidt-mhp I'm reluctant to any kind of implicit inheritance like that. It's easy to get it wrong with that and frankly speaking brings no benefits. Consider an opposite situation when you have two decorators on the root and apis level, and you actually want to completely replace the parameters:

```yaml

decorators:
  foo:
    prop1: 1
    prop2: 2
apis:
  override@v1:
     decorators:
        foo:
           prop3: 3 # <-- I actually want only this property and not prop1 & prop2

```

It would be harder (if at all possible) to redefine them as I have to explicitly provide them with `null` values or something.
