### ISSUE TITLE
Support JSON-schema assertion in configurable rules

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#1886]
**Is your feature request related to a problem? Please describe.**

Some people maintain JSON schemas to validate some parts of OpenAPI. We don't have a way to use them.

**Describe the solution you'd like**

I would like to add support for json schema assertion for our configurable rules. It may look like this:

```
rule/info-metadata-check:
  subject:
    type: Info
    property: x-metadata
  message: Metadata should match the schema.
  assertions:
    json-shema:
      $ref: ./metadata-schema.json
```

**Describe alternatives you've considered**

Right now it is possible to achieve using custom assertions/rules via plugin: https://redocly.com/docs/cli/rules/configurable-rules#custom-function-example

**Additional context**

Reported in Write the Docs slack: https://writethedocs.slack.com/archives/C4EPE8332/p1738793608940479
