### ISSUE TITLE
[lint-ignore][feature] wildcard path to ignored files

### ISSUE THREAD

**Issue by Thiebosh** [Redocly/redocly-cli#1888]
**Is your feature request related to a problem? Please describe.**

I work with a big api (~500 enpoints and ~1400 jsonSchemas) and for jsonSchemas, we use special keywords at root level for specific use (ihm, code gen...) that are out of openapi specification. Since @redocly/cli@1.25.15, the struct rule is triggered by those special keywords, which cause the linter to output +10k errors (or warning, depending on severity setted), all linked to them.

our problems : 
- We tried to customize the rule without luck
- We can't use (maintain) the lint-ignore file since he is too big (~5k lines) because of the precise relative paths
- We want to keep the structure rule validation

**Describe the solution you'd like**

The simplest solution would be to use wildcards in lint-ignore file. It would allow us to go from : 
```
openapi/components/schemas/domainA/subDomainA/objectA.json:
  struct:
    - '#/javaType'
openapi/components/schemas/domainA/subDomainA/subsubDomainA/objectAA.json:
  struct:
    - '#/javaType'
...
openapi/components/schemas/domainA/subDomainZ/subsubDomainZ/objectZY.json:
  struct:
    - '#/javaType'
```
to something like : 
```

openapi/components/schemas/**/*.json:
  struct:
    - '#/javaType'
```
or with magic matchers : 
```
_schema.yaml:
  struct:
    - '#/javaType'
_schema.json:
  struct:
    - '#/javaType'
```

**Describe alternatives you've considered**

We tried to customize struct rule, or to turn it off and fork it's code from redocly repository, but we simply turned it off to keep the lib up to date

**Additional context**

wildcards are already in use for join command

**Comment by tatomyr** [comment]
@Thiebosh looks like you're looking for the wrong solution for your problem 🙂. Instead of ignoring the errors, you can extend the existing `Schema` type using [typeExtension](https://redocly.com/docs/cli/custom-plugins/extended-types). 

Your plugin might look like this:

```js
export default () => ({
  id: 'my-type-extension',
  typeExtension: {
    oas3(types) {
      return {
        ...types,
        Schema: {
          ...types.Schema,
          properties: {
            ...types.Schema.properties,
            javaType: { type: 'string' }, // <-- here you extend the predefined type with the keywords you need to add.
          },
        },
      };
    },
  },
});

```

**Comment by drewish** [comment]
I'd love the ability to use wildcards to be able to apply ignores to multiple files (we generate a new filename for each environment). I the other option that would be if the YAML parser supported the full spec and I could use YAML anchors to share a list:
```
struct_rules: &struct_rules
    - '#/components/schemas/EventResponsePublicDto/properties/metadata/properties/dto/nullable'
    # ... 
docs/local.json:
    no-server-example.com:
        - '#/servers/0/url'
    struct: *struct_rules
docs/dev.json:
    struct: *struct_rules
docs/prod.json:
    struct: *struct_rules
```

**Comment by drewish** [comment]
Oh turns out it the js-yaml library supports anchors. I had to do a little tweaking to the structure but got it working:
```
docs/local.json:
    no-server-example.com:
        - '#/servers/0/url'
    struct: &struct_rules
        - '#/components/schemas/EventResponsePublicDto/properties/metadata/properties/dto/nullable'
        # ... 
docs/dev.json:
    struct: *struct_rules
docs/prod.json:
    struct: *struct_rules
```
