### ISSUE TITLE
Respect command option server should handle multi-server

### ISSUE THREAD

**Issue by sjbenoist** [Redocly/redocly-cli#2027]
**Is your feature request related to a problem? Please describe.**

As specified in the documentation here https://redocly.com/docs/respect/commands/respect
the --server option enables us to override a server from an OpenAPI  sourceDescription.
The option format is <name>=<url> where name is the source name and the url the address to use instead of whatever server url may be present inside the OAS file,

There is no clear mechanism to specify which server URL should be used in the absence of this --server option. Is respect going to use the first found url in the OAS file ? Since we frequently specify production and sandbox servers for our clients, we see no reliable mean to avoid unwanted calls to the production urls.

With that in mind, we need to force a server override to prevent such issues. As we systematically have an OAS file for the API itself and one for the Authorization server - OAuth2 based -, we need to force both server URLs to point to the proper endpoint, 

We have not found a way to specify two overrides values for the --server option (using ';', ',')

**Describe the solution you'd like**

Extend the --server option to support multiple values, separated by any means, like

--server api1=http://address1.com:8000; api2=http://address2.com:8443

**Comment by DmitryAnansky** [comment]
Hello @sjbenoist ,
We support multiple servers override with cli command options, but it must be mapped to sourceDescription name.
Here is the possible formats you can use

- `REDOCLY_CLI_RESPECT_SERVER="museum-api=https://smth.com/,tickets-from-museum-api=https://smth.com/" redocly respect examples/museum-api/museum-api-test.yaml`

- `redocly respect examples/museum-api/museum-api-test.yaml --server museum-api="https://smth.com" --server tickets-from-museum-api="https://smth.com"`

- `redocly respect examples/museum-api/museum-api-test.yaml --server museum-api="https://smth.com" --server tickets-from-museum-api="https://smth.com"`

- `redocly respect examples/museum-api/museum-api-test.yaml --server='{"museum-api":"https://smth.com/","tickets-from-museum-api":"https://smth.com/"}'`

- `redocly respect examples/museum-api/museum-api-test.yaml --server='museum-api=https://smth.com/"' --server='tickets-from-museum-api="https://smth.com/"'`


The default behavior is to take first available server from OpenAPI description if you don't provide overrides.
Also you can check this  [x-server-url extension](https://redocly.com/docs/respect/extensions/x-server-url).
With the extension you could override serverUrl inside Arazzo file, like in those examples:

```
sourceDescriptions:
  - name: museumAPI
    url: https://github.com/Redocly/museum-openapi-example/blob/main/openapi.yaml
    type: openapi
    x-serverUrl: https://test-lab1.example.com
```
or
```
sourceDescriptions:
  - name: museumAPI
    url: https://github.com/Redocly/museum-openapi-example/blob/main/openapi.yaml
    type: openapi
    x-serverUrl: $servers.1.url
```

Please let us know if it works for you.
