### ISSUE TITLE
Redocly lint fails with an error 'Expected type `object,null` but got `object`.'

### ISSUE THREAD

**Issue by ZyzychO** [Redocly/redocly-cli#2104]
**Describe the bug**

With the following schema in openapi: 3.1.1 

```yaml
    pet:
      title: petapi
      type: object
      description: this is pet api
      properties:
        constructor:
          title: petapi
          type:
            - object
            - 'null'
```

Redocly CLI lint command fails with an error message:  'Expected type `object,null` but got `object`.' If you change the 'type' into 'types', lint is passing.

**To Reproduce**

1. Use the following openapi.yaml file: 

```yaml
openapi: 3.1.1
info:
  title: Pet API
  version: 1.0.0
  description: A simple API for pet-related contracts.

paths:
  /pets:
    get:
      summary: Get pet contract information
      operationId: getPet
      responses:
        '200':
          description: Successful response with pet contract
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pet'

components:
  schemas:
    pet:
      title: petapi
      type: object
      description: this is pet api
      properties:
        constructor:
          title: petapi
          type:
            - object
            - 'null'
```
2. Execute Redocly lint command
3. See error

**Expected behavior**

Lint should pass

**Logs**

**OpenAPI description**

Configuration in redocly.yaml file:
```yaml

extends:
  - minimal
```

**Redocly Version(s)**

1.33.0

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fy40zw)

**Comment by tatomyr** [comment]
@ZyzychO as an immediate workaround, you can change the schema the following way to eliminate the error (it's an alternative way of describing the same data structure):

```yaml
    pet:
      title: petapi
      type: object
      description: this is pet api
      properties:
        constructor:
          title: petapi
          oneOf:
            - type: object
            - type: 'null'

```

> If you change the 'type' into 'types', lint is passing.

I believe it doesn't matter how you change the name of that property. Redocly CLI specifically check only for the `type` property, so the error disappears because there's no such one.

**Comment by tatomyr** [comment]
It seems that support for that syntax was never implemented.

**Comment by adamaltman** [comment]
This is a valid syntax we have other users that use it. We should update the priority on this issue. It is particularly common with null and another type since they eliminated nullable in 3.1.

**Comment by adamaltman** [comment]
Is the issue specific to

```
- object
- 'null'
```

Or also applies to other types combined like the following:

```
- string
- 'null'
```

**Comment by tatomyr** [comment]
The same issue will occur with any schema that uses the array type syntax instead of `oneOf`. For example, the following will also produce a similar error:

```yaml
type: 
- string
- number
```

**Comment by RomanHotsiy** [comment]
It's p1 or p2 at least.

**Comment by RomanHotsiy** [comment]
> It seems that support for that syntax was never implemented.

This is not correct. It does work and was implemented a while ago. The problem is with the `constructor` keyword.

I you replace it with anything else it works just fine:

```
components:
  schemas:
    pet:
      title: petapi
      type: object
      description: this is pet api
      properties:
        constructor2:
          title: petapi
          type:
            - object
            - 'null'
```
