### ISSUE TITLE
Path parameter isn't defined

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#211]
**Describe the bug**
If a path has a named placeholder but doesn't have a path parameter, then we should show the problem.

> Each template expression in the path MUST correspond to a path parameter that is included in the Path Item itself and/or in each of the Path Item's Operations.

**To Reproduce**
1. Given this `.redocly.yaml` file (just the `recommended` rules)
2. Contact Adam or see a sample below.
3. Run this command with these arguments... `openapi lint`
4. See no error

**Expected behavior**
I expect to see this error: https://redoc.ly/docs/cli/built-in-rules/#path-parameters-defined

**Logs**

```
validating /home/adam/Downloads/2020-09-23-13-03-openapi-od_3p8p9x.yaml...
/home/adam/Downloads/2020-09-23-13-03-openapi-od_3p8p9x.yaml: validated in in 86ms

Woohoo! Your OpenAPI definition is valid. 🎉
```

**OpenAPI definition**

This is an excerpt.

The one with the path template was defined first:
```
paths:
  /something/{id}:
   parameters:
     - name: foo
       in: header
       required: true
       schema:
         type: string
  /something:
# ...
```

**`openapi-cli` Version(s)**
1.0.0-beta.14

**`Node.js` Version(s)**
v12.6.0

**Additional context**

Contact Adam if you need a full OpenAPI definition.
