### ISSUE TITLE
Digest Authorization header have bigger priority despite it described before another authorization

### ISSUE THREAD

**Issue by DmitryAnansky** [Redocly/redocly-cli#2124]
### **Describe the bug**

Digest Authorization header has higher priority despite being described before another authorization type.  
So if this type of Authorization is used, it always overrides the last `Authorization` header.

### **To Reproduce**

1. Given this `x-security` description:
```yaml
   x-security:
     - scheme:
         type: http
         scheme: digest
       values:
         username: $inputs.name
         password: secret
     - scheme:
         type: apiKey
         name: Authorization
         in: header
       values:
         value: $inputs.secret
```
2. When `respect` executed, digest auth header override API-Key header, although it should have bigger priority

### **Expected behavior**

`x-security` header resolution should follow top-to-bottom order, with the bottom entry having higher priority.
