### ISSUE TITLE
The apis keyword in configuration should support a reserved default keyword

### ISSUE THREAD

**Issue by darcyrush** [Redocly/redocly-cli#2136]
**Is your feature request related to a problem? Please describe.**

Unless i am misunderstanding the [configuration documentation](https://redocly.com/docs/cli/configuration), only OpenAPI schemas that are defined in `apis` with a `root` path will be linted. Any OpenAPI schemas not defined in `apis` will be completely ignored. 

This is painful when new OpenAPI schemas are created and linting passes, since the PR can be merged but the newest OpenAPI schema is full of errors.

**Describe the solution you'd like**

A reserved keyword like `default` for use with the `apis` keyword, which can also use `$ref` to point to a file with custom rules and extends that can be set like any other api configuration (minus the `root` keyword, or perhaps the `root` keyword accepts a `*` wildcard). 

This keyword will act as a matching fallback when any schemas are found by the `lint` command that do not match any `root` paths defined in the configuration.

```yaml
# redocly.yaml
apis:
  example@v1:
    $ref: ./configuration/example.v1.yaml
  default@*:
    $ref: ./configuration/default.yaml

# example.v1.yaml
root: ./openapi/example.v1.openapi.json
extends:
  - minimal
rules:
  info-licence: off

# default.yaml
# root ./openapi/*.openapi.json
extends:
  - recommended
rules:
  some-optional-rule: error
```

**Describe alternatives you've considered**

If this is already possible in some way, improve the documentation

**Additional context**
