### ISSUE TITLE
Invalid example reference

### ISSUE THREAD

**Issue by bu4ak** [Redocly/redocly-cli#259]
**Describe the bug**
Generates a relative path to a file instead of a link to a components. 

**To Reproduce**
1. file index.yaml
```yaml
openapi: 3.0.3
info:
    version: 3.0.0
components:
    schemas:
        $ref: "./networks.yaml"
```
2. file network.yaml
```yaml
type: object
description: Network
required:
    - id
    - network

properties:
    id:
        type: integer
    network:
        type: string
        description: social network name

example:
    id: 25
    network: social
```
3. file networks.yaml
```yaml
type: array
items:
    $ref: "./network.yaml"

example:
    -   $ref: "./network.yaml#/example"

```
4. Run `openapi bundle index.yaml --output output/test.yaml --ext yaml` command
5. See error (in swagger editor) **Resolver error at components.schemas.networks.example.0.$ref
Could not resolve reference: Tried to resolve a relative URL, without having a basePath. path: './network.yaml' basePath: 'undefined'**

**Expected result**
```yaml
    networks:
      type: array
      items:
        $ref: '#/components/schemas/network'
      example:
        - $ref: '#/components/schemas/network/example'
```
**Actual result**
```yaml
    networks:
      type: array
      items:
        $ref: '#/components/schemas/network'
      example:
        - $ref: ./network.yaml#/example
```

**`openapi-cli` Version(s)**
^1.0.0-beta.32

**`Node.js` Version(s)**
v14.15.5

**`npm` Version(s)**
7.6.0

**Additional context**
![image](https://user-images.githubusercontent.com/17143820/109663767-c06d3900-7b6c-11eb-82b8-6abf082597ac.png)
![image](https://user-images.githubusercontent.com/17143820/109663787-c5ca8380-7b6c-11eb-92f4-7390d248feff.png)
