### ISSUE TITLE
Allow adding refs from pre-processors

### ISSUE THREAD

**Issue by konstantin-smolyakov-idt** [Redocly/redocly-cli#324]
**Is your feature request related to a problem? Please describe.**
I would like to implement a custom plugin to conventionally add responses to each operation. For example, I would like to add 400 errors to all operations in my spec without having to specify it each time. 

**Describe the solution you'd like**

Let's imagine a configuration file with the following entries. It will mean that all operations can return 400 or 422. Potentially, this can be extended with a filter to include only certain operations by convention (e.g. a delete request might not return 400 error).
```
preprocessors:
    my-custom-pluging/conventional-response:
      '422':
        response:
          $ref: './common/errors/validation-error.response.yaml'
      '400':
        response:
          $ref: './common/errors/bad-request-error.response.yaml'
```
I've tried to implement a PoC for this, but it appears that references are all processed before any plugins are invoked. So I end up with `Can't resolve $ref` error messages from the bundler. 

**Describe alternatives you've considered**
The alternative will be to build a rule to enforce this. But this is not the same, because there is no way to auto-fix the issue and it adds some churn on the developer to remember to add all standard errors to operations. 

**Additional context**
I understand that this might not go well with the idea of reporting the precise error location in case other validators run on post-processed results. However, maybe it can be solved by restoring the post-processed tree somewhere in the temporary folder and pointing issues there.
