### ISSUE TITLE
join command creating _other tags unnecessarily

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/redocly-cli#354]
**Describe the bug**
I just successfully ran `openapi join` on a set of OAS definitions for the first time. It very nicely joined all of the files into a single file without any errors or warnings. For every tag that was in the original files, though, the resulting openap.yaml file contained that tag and another one named {tag-name}_other. For example:

```
tags:
  - name: account-label
    x-displayName: account-label
  - name: account-label_other
    x-displayName: other
  - name: adjustment
    x-displayName: adjustment
  - name: adjustment_other
    x-displayName: other
```

All operations in the input files have tags assigned to them. In the openapi.yaml file, there are no operations that have any of these _other tags assigned to them. So, the _other tags are never used, and based on my reading of the [join description](https://redoc.ly/docs/cli/commands/join/), they shouldn't have been created.

**Expected behavior**
No _other tags are created when all operations in input files already have tags.

**`openapi-cli` Version(s)**
1.0.0.beta.54
