### ISSUE TITLE
`request-mime-type` and `response-mime-type` built-in rule

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#393]
**Is your feature request related to a problem? Please describe.**

People may want to enforce a specific request and response mime-type (they may be distinct values).

**Describe the solution you'd like**

```
lint:
  rules:
    request-mime-type:
       severity: error
       allowedValues:
          - application/json
    response-mime-type:
       severity: error
       allowedValues:
          - application/json
          - application/problem+json
```

**Describe alternatives you've considered**
None

**Additional context**
none
