### ISSUE TITLE
`tag-description-override` built-in decorator

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#398]
**Is your feature request related to a problem? Please describe.**

See #397 

**Describe the solution you'd like**

```
lint:
  decorators:
    tag-description-override:
      Customers: ./customer-tag-description.md
      Orders: ./order-tag-description.md
```

The value of the decorator is a map of tag name => path to Markdown file with the tag description.

**Describe alternatives you've considered**
- Inline Markdown.

**Additional context**

#397
