### ISSUE TITLE
`media-type-examples-override` decorator

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#440]
**Is your feature request related to a problem? Please describe.**

To solve the same issue we solved with other decorators. 

Most developers are too lazy to define media type examples.

https://github.com/redocly-demo/decorators-demo/pull/1

In the event the OpenAPI file is auto-generated, then there is no reliable way to add examples (without them getting overwritten on the next auto-generation).

**Describe the solution you'd like**

I'd like to see:

```
decorators:
  media-type-examples-override:
    operationIds:
      PostPets: ./pet-examples.yaml
```

**Describe alternatives you've considered**
None - I am open to ideas.

**Comment by IgorKarpiuk** [comment]
@adamaltman What should we do if we have few media type examples in one operation?

For example: 
```yaml
responses:
        200:
          description: json
          content:
            application/json:
              examples:
                 test1:
                   value:
                     a: test1
                     b: 35
        201:
          description: xml
          content:
            application/xml:
              examples:
                test2:
                  value:
                   a: test2
```

**Comment by tatomyr** [comment]
@adamaltman , @RomanHotsiy any thoughts?

**Comment by RomanHotsiy** [comment]
There is also request body example.

I'm not sure. @adamaltman what was your idea about the format of `./pet-examples.yaml` file? Was it supposed to have multiple examples somehow?

**Comment by adamaltman** [comment]
Yes, it can have multiple examples. However, that's a good question. It needs to target the response code or the request media type.

So maybe it should be like this:
```
decorators:
  media-type-examples-override:
    operationIds:
      '200':
         PostPets: ./pet-examples.yaml
      '400':
         PostPets: ./pet-errors-examples.yaml

```
