### ISSUE TITLE
new decorators: `filter-in` and `filter-out`

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#599]
**Is your feature request related to a problem? Please describe.**
Users need to generate different "slices" of single OpenAPI definition for different audiences.

For example, "include only API endpoints with `x-audience` set to `public`".

This is more advanced version of [`remove-x-internal`](https://redocly.com/docs/cli/resources/built-in-decorators/#remove-x-internal) which covers only basic use case.

**Describe the solution you'd like**
We need two decorators `filter-in` and `filter-out`.

### `filter-in`

Keep nodes that have specific property set to the specific value. Arrays should be supported too.
If the property is not set on the node it should be kept too.

```yaml
filter-in:
  property: x-audience
  value: [Public, Partner] 
```

In the example above `value` should support arrays. If `x-audience` in the definition is an array too the node should be kept if only two arrays have **at least one** element in common. We can implement `matchStrategy` option to alter this behavior with values: 'any' or 'all'.

### `filter-out`

It's same as `filter-in` but it removes nodes that have specific property set to the specific value.

```yaml
filter-out:
  property: x-audience
  value: Private 
```

**Describe alternatives you've considered**
`filter-out-permission` and `filter-in-permission`

**Additional context**

**Comment by adamaltman** [comment]
I like this. I think `matchStrategy` could be quite good too, but oneOf seems wrong to me -- or rather, we would need oneOf, anyOf, and allOf. 

The oneOf strategy would match when the intersection has one and only one value.

The anyOf strategy would match when the intersection has one or more values.

The allOf strategy would match when the intersection has all the values.

**Comment by RomanHotsiy** [comment]
How about `every` and `some` as an alternative for `matchStrategy`?

**Comment by adamaltman** [comment]
I think `all` is more clear than `every`. It could be just `all` and `any`.

**Comment by adamaltman** [comment]
Also, I think we need `filter-operations` too.

**Comment by RomanHotsiy** [comment]
@adamaltman could you elaborate a little bit?

**Comment by adamaltman** [comment]
My case can be solved like:

```yaml
filter-in:
  property: operationId
  value: [PostCustomer, DeleteCustomer] 
```

**Comment by RomanHotsiy** [comment]
Another interesting use-case: splitting single source of truth definition into smaller chunks by tags:

```
apis:
  users@v1:
    root: ./big-oas.yaml
    lint:
      decorators:
        filter-in:
          property: tags
          value: [Users, Account] 
  payments@v1:
    root: ./big-oas.yaml # same root
    lint:
      decorators:
        filter-in:
          property: tags
          value: [Payments, CreditCards, Transactions] 
  ```
