### ISSUE TITLE
Header component improperly flagged as not meeting spec

### ISSUE THREAD

**Issue by atzawada** [Redocly/redocly-cli#611]
**Describe the bug**
When defining a common header in an OASv3 doc, the CLI flags both the `name` and `in` field as required when they are not allowed in the spec, per https://swagger.io/specification/#header-object

**To Reproduce**
* Add the following to an OASv3 doc:
```yaml
components:
  headers:
    X-Application-Msg-ID:
      description: An optional message ID that can be used to debug calls to the API
      schema:
        type: string
```
* lint using the CLI

The header object will be flagged by the `spec` rule for not having the `name` and `in` fields.

**Expected behavior**
These fields should not be flagged as they are not permitted in the OASv3 schema.

**`openapi-cli` Version(s)**
`1.0.0-beta.91`

**`Node.js` Version(s)**
`v16.13.1`
