### ISSUE TITLE
`join` command regression: decorators/preprocessor are always executed

### ISSUE THREAD

**Issue by acote-coveo** [Redocly/redocly-cli#641]
**Describe the bug**

Before [this commit](https://github.com/Redocly/openapi-cli/commit/b53e9e4acbd694ac4b0aa4c8f09fc4c5b6f95901), the join command wasn't bundling documents. By changing this behaviour, running a join now always execute the decorators/preprocessor. 

For us, it's a regression because we use decorators to remove internal documentation. So with the latest versions, we have no way to join ours different api files and keep the internal documentation conditionally.

**To Reproduce**

> openapi join file1.yaml file2.yaml

**Expected behavior**

It was expected that bundling wasn't part of the join command. From my understand, the bundling mechanism was only to resolve reference properly in the join command. Perhaps the join command could ignore the decorators/preprocessor from the config or we could support similar bundle parameters such as `--skip-decorators`

**Logs**
If applicable, add logs to help explain your problem.

**OpenAPI definition**

_.redocly.yaml_:

```yaml
lint:
  extends:
    - minimal
  plugins:
    - './build/openapi-plugins/decorators.js'
  decorators:
    cleanup/remove-hidden: error
    cleanup/remove-internal: error
```

**`openapi-cli` Version(s)**
beta-94

**`Node.js` Version(s)**
N/A -> Running in docker

**Additional context**

**Comment by adamaltman** [comment]
That comment (with the bundling) was done to solve https://github.com/Redocly/openapi-cli/issues/339

There is a workaround you can do. In newer versions of OpenAPI-cli we support a new configuration file format.

```
apis:
  other@internal:
    root: ./other.yaml
  example@internal:
    root: ./openapi.yaml
  example@external:
    root: ./openapi.yaml
    lint:
      decorators:
        cleanup/remove-hidden: error
        cleanup/remove-internal: error
lint:
  plugins:
    - './build/openapi-plugins/decorators.js'
  extends:
     - minimal
```

In this case, you could use the `@internal` API for the join and the `@external` for some external documentation purpose.

Here is a lightweight example of using the same root file with different decorators:

https://github.com/redocly-demo/demo-remove-x-internal
