### ISSUE TITLE
Add warning if oneOf, allOf or anyOf has a only one element in recommended configuration

### ISSUE THREAD

**Issue by lucianojs** [Redocly/redocly-cli#683]
**Is your feature request related to a problem? Please describe.**
Add warning if oneOf, allOf or anyOf has a only one element in recommended configuration

In this case are not sense to mantain this keywords in the spec

**Comment by adamaltman** [comment]
Good idea. I see the `allOf` situation often, and wonder...

**Comment by adamaltman** [comment]
Came across this issue twice again today (with `allOf`).

```yaml
myProperty:
  allOf:
    - $ref: ./my-object.yaml
```
Should be like:

```yaml
myProperty:
  $ref: ./my-object.yaml
```

**Comment by jeremyfiel** [comment]
I would argue the use of allOf with a single reference is used quite heavily for adding sibling elements when using OAS 3.0.x. Without the allOf, the description and default are ignored, with the allOf, they are evaluated successfully.

```yaml
myProperty:
  allOf: 
    - $ref: ./my-object.yaml
    description: here's my description
    default: xyz
```

This was later fixed in OAS 3.1.0 with full JSON support.
