### ISSUE TITLE
required assertion not functional

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#684]
**Describe the bug**

The required assertion is not functional. The mutuallyRequired assertion is functional.

**To Reproduce**
1. Given the `.redocly.yaml` and `openapi.yaml` file below...
1. Run `lint` and see the lack of any error.

**Expected behavior**

I expected to can an error:

> Must define 200 and 201 responses for PUT requests.

**OpenAPI definition**

`redocly.yaml` file

```yaml
apis:
  repro@v1:
    root: openapi.yaml

lint:
  extends: []
  rules:
    assert/put-200-and-201-required:
      subject: ResponseMap
      context:
        - type: Operation
          matchParentKeys:
            - put
      message: Must define 200 and 201 responses for PUT requests.
      severity: error
      required:
        - '200'
        - '201'
```

`openapi.yaml` file (minimal reproduction file)

```yaml
openapi: 3.0.3
info:
  title: Repro assertion error
  version: v1
paths: 
  /:
    put:
      summary: Demo problem with required assertion
      responses: 
        # '200':
        #   description: OK
        # '201':
        #   description: CREATED  
        '400':
          description: Bad request
```

**Redocly Version(s)**

1.0.0-beta.97

**`Node.js` Version(s)**

v16.10.0

**Additional context**

I was testing the docs when I noticed this issue.
