### ISSUE TITLE
`requireOne` assertion

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#711]
**Is your feature request related to a problem? Please describe.**
I want to be able to assert that **at least** one of the specified properties exists.

This is different from `mutuallyExclusive` as mutuallyExclusive does not require any of the properties should exists. 

**Describe the solution you'd like**

Add to the `Assertion Object`:
| Property | Type | Description |
|---|---|---|
|requireOne| [`string`] | Asserts that at least one of the listed properties (key names only) is defined.| 

Simple example

```yaml
subject: MediaType
requireOne:
  - example
  - examples
```
Example in combination with mutuallyExclusive
```yaml
subject: MediaType
mutuallyExclusive:
  - example
  - examples
requireOne:
  - example
  - examples
```

**Describe alternatives you've considered**
None.

**Additional context**
-
