### ISSUE TITLE
[Lint] Ability to treat warnings as errors and return non-0 exit code

### ISSUE THREAD

**Issue by welandaz** [Redocly/redocly-cli#747]
**Describe the solution you'd like**
It would be really nice to have an ability to treat lint warnings as errors and return non-0 exit code.

This would be beneficial for the cases where one want's to know whether there are any issues with the document
in general (both errors and warnings) and return code could signal that.

**Describe alternatives you've considered**
This feature could be enabled by an additional flag to the "lint" command (everything else would stay the same, but if there are 0 errors and at least 1 warning - non-0 exit code is returned)

**Comment by adamaltman** [comment]
@welandaz why not configure your rules to have errors instead of warnings?

This is the "recommended" rules:

```yaml
lint:
  rules:
    info-description: warn
    info-contact: off
    info-license: warn
    info-license-url: warn
    tag-description: warn
    tags-alphabetical: off
    parameter-description: off
    no-path-trailing-slash: error
    no-ambiguous-paths: warn
    path-declaration-must-exist: error
    path-not-include-query: error
    path-parameters-defined: error
    operation-description: off
    operation-2xx-response: warn
    operation-4xx-response: warn
    operation-operationId: warn
    operation-summary: error
    operation-operationId-unique: error
    operation-operationId-url-safe: error
    operation-parameters-unique: error
    operation-tag-defined: off
    operation-security-defined: error
    operation-singular-tag: off
    no-unresolved-refs: error
    no-enum-type-mismatch: error
    boolean-parameter-prefixes: off
    paths-kebab-case: off
    spec: error
    no-invalid-media-type-examples:
      severity: warn
      disallowAdditionalProperties: true
    no-server-example.com: warn
    no-server-trailing-slash: error
    no-empty-servers: error
    no-example-value-and-externalValue: error
    no-unused-components: warn
    no-undefined-server-variable: error
```

You could find/replace "warn" to "error".
