### ISSUE TITLE
join command lists tags in output OpenAPI multiple times

### ISSUE THREAD

**Issue by richiksc** [Redocly/redocly-cli#755]
**Describe the bug**
Tags are duplicated multiple times in output OpenAPI, even if the tags are not duplicated across the input files (only one Tag definition in one source OpenAPI file).

**To Reproduce**
```
openapi join api1.yaml api2.yaml
```
See output:

```yaml
tags:
  - name: Event
    description: [redacted]
    x-displayName: Event
  - name: Session
    description: [redacted]
    x-displayName: Session
  - name: Session
    x-displayName: Session
  - name: Session
    x-displayName: Session
  - name: Event
    x-displayName: Event
  - name: Event
    x-displayName: Event
  - name: Event
    x-displayName: Event
  - name: Event
    x-displayName: Event
  - name: Event
    x-displayName: Event
```

**Expected behavior**
Tags listed in only one input file are not duplicated.

**Logs**
If applicable, add logs to help explain your problem.

**OpenAPI definition**
If applicable, add an OpenAPI definition and `.redocly.yaml` configuration file that helps reproduce the problem.
At a minimum, please state the specification version(s) you're using (e.g. 2.0, 3.0, 3.1).

**Redocly Version(s)**
What version of Redocly CLI are you using?
```
% openapi --version
1.0.0-beta.103
```

**`Node.js` Version(s)**
What version of `node.js` are you using?
```
% node --version
v16.15.1
```
