### ISSUE TITLE
Examples field is not validated against openAPI 3.0.0 spec

### ISSUE THREAD

**Issue by azimbelm** [Redocly/redocly-cli#757]
**Describe the bug**
No validation rule applies on the "Examples" field name defined in
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#exampleObject
--> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

**To Reproduce**
I created an openapi.yaml containing the following lines

```
parameters:
    - name: identifier
    - required: true
          in: path
          allowEmptyValue: false
          description: Some description
          examples:
            valid identifier:
              description: 'Some description'
              value: '49039557299384'
```

Running 'redocly lint openapi.yaml' returns that the file is valid.

The field name '**valid identifier**' within the examples is invalid but I could not find any rule detecting this.
An custom built assertion rule did not work because it only works for the value of a given property.

**Expected behavior**
An error should be shown, that the 'valid identifier' is invalid

**OpenAPI definition**
 .redocly.yaml
```
lint:
  extends:
    - all
```

Specification version used: 3.0.0

**Redocly Version(s)**
**v1.0.0-beta.103**

**`Node.js` Version(s)**
**v16.12.0**

**Comment by tatomyr** [comment]
Thanks @azimbelm for pointing this out. 
This would have been possible to validate via an assertion like this:
```yaml
assert/example-name-format:
      subject: ExampleMap
      pattern: ^[a-zA-Z0-9.-_]+$
```

However, at the moment `ExampleMap` and a few others aren't available. I think this should be fixed. Will create an issue for that.
