### ISSUE TITLE
Change context to if and change the object definition

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#781]
**Is your feature request related to a problem? Please describe.**

The context object allows for targeting exact keys. However, sometimes you need more flexibility and want to target based on some specific parent property value 

**Describe the solution you'd like**

## Context object (current)

Property | Type | Description
-- | -- | --
type | `string` | **REQUIRED.** One of the [OpenAPI node types](#openapi-node-types).
matchParentKeys | [`string`] | The list of parent object key names to evaluate with respect to the subject.
excludeParentKeys | [`string`] | The list of parent object key names to not evaluate with respect to the subject.

## Context object (desired)

Property | Type | Description
-- | -- | --
type | `string` | **REQUIRED.** One of the [OpenAPI node types](#openapi-node-types).
includeParentKeys | [`string`] | The list of the exact parent object key names to evaluate with respect to the subject.
excludeParentKeys | [`string`] | The list of the exact parent object key names to not evaluate with respect to the subject.
includeByPropValue | [PropMatcher] | A list of prop matchers. They are combined using boolean AND. Subject is evaluated if all the matchers apply.
excludeByPropValue | [PropMatcher] | A list of prop matchers. They are combined using boolean AND. Subject is not evaluated if all the matchers apply.

## PropMatcher object (desired)
Property | Type | Description
-- | -- | --
key | `string` | **REQUIRED.** The property key
value | `any` | [`any`] | The property value to match. Supports only scalar values. If `value` is an array then the prop value should match at least one item.

Example usage:

```yaml
assert/only-string-in-params:
  context:
  - type: Operation
    matchParentKeys: [put]
  - type: Parameter
    includeByPropValue:
      - key: in # we can validate the key value!
        value: ["query", "path"]
  subject: Schema
  property: type
  enum: ["string"]
```

**Describe alternatives you've considered**

Make it a bit more simple without support for multiple matchers.

**Additional context**

Related to https://github.com/Redocly/redocly-cli/issues/714
Some more context in: https://github.com/Redocly/intranet/issues/370#issuecomment-1196703294
