### ISSUE TITLE
matchesJsonSchemaType incorrect results for type `any`

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#785]
**Describe the bug**

This function `matchesJsonSchemaType` returns incorrect results for type `any`.

**To Reproduce**
1. Given a schema with type `any`.
2. Add some enum values, and check the `no-enum-type-mismatched` rule for example.
3. See error

**Expected behavior**

Any type of value should be acceptable for type any.

**Logs**

n/a

**OpenAPI definition**

```yaml
schema:
  type: object
  properties:
    demo:
      type: any
      enum: ['string', 123]
```

**Redocly Version(s)**

1.0.0-beta.105

**`Node.js` Version(s)**

16

**Additional context**
