### ISSUE TITLE
Wrong report position on `path-excludes-patterns` rule

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#794]
**Describe the bug**

Rule `path-excludes-patterns` reports on `PathItem` value instead of a key when referencing the `PathItem` value.

**To Reproduce**
1. Given this `.redocly.yaml` file:
```yaml
styleguide: 
  extends: []
  rules: 
    path-excludes-patterns: 
      severity: error
      patterns:
        - \/WRONG

```
2. And this OpenAPI file(s)
```yaml 
# openapi.yaml
openapi: 3.0.0
paths:
  '/WRONG':
    $ref: value.yaml
```

```yaml 
# value.yaml
get:
  summary: wrong get
```
3. Run this command with these arguments... `redocly lint openapi.yaml`

**Expected behavior**

It should report on the `PathItem` key (e. g. `/WRONG:`) as it does for not referenced paths items.

**Redocly Version(s)**
1.0.0-beta.105

**`Node.js` Version(s)**
v16.14.0

**Comment by tatomyr** [comment]
I wonder if we could deprecate this rule in favour of a custom rule. This will work even better:

```yaml
rules:
  rule/path-exclude:
    subject: 
      type: Paths
    assertions: 
      notPattern: \/WRONG
```
