### ISSUE TITLE
Assertions `pattern` evaluates the key names of the subject's children, not the key names of the subject

### ISSUE THREAD

**Issue by tatomyr** [Redocly/redocly-cli#805]
**Describe the bug**
Using assertions, I want to detect `PathItems ` which keys match some pattern. According to [the docs](https://redocly.com/docs/cli/rules/assertions/#assertion-object), if `property` key isn't specified, assertions should evaluate against the key names for the subject node type.
However, if I write this:

```yaml
assert/path-excludes-patterns2: 
      severity: error
      subject: PathItem
      pattern: ^\/(?!GET).*
```

it actually match against the `Operation` keys (`get`, `post` &c.).

**To Reproduce**
1. Given the `redocly.yaml` file with the assertion above
2. And this OpenAPI file: https://github.com/Redocly/redocly-cli/blob/master/resources/pets.yaml
3. Run `redocly lint pets.yaml`
4. See it doesn't detect the correct `PathItems` 

**Expected behavior**
If `property` key is not provided, assertion should evaluate against the key names for the subject node type.

**Redocly Version(s)**

`1.0.0-beta.106`

**`Node.js` Version(s)**
`16`

**Comment by RomanHotsiy** [comment]
You're trying to match parent key here. But pattern matches keys of the object itself. This is expected behaviour.

It can be fixed by adjusting the assertion:

```yaml
assert/path-excludes-patterns2: 
      severity: error
      subject: PathMap
      pattern: ^\/(?!GET).*
```
