### ISSUE TITLE
Question: custom rules with assertions syntax

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#817]
I'm writing a custom rule based on the example [response-contains-property](https://redocly.com/docs/cli/guides/response-contains-property)

I'm using OAS 3.0.3, my response is using a `$ref` to an external JSON Schema Draft-04.  In order for this rule to work, do I need to dereference the definition prior to linting?  It seems to be returning from the `schema.type !== 'object'` condition and doesn't report any error when using the `lint` command. 

```json
"responses": {
	"200": {
		"description": "Ok",
		"content": {
			"application/json": {
				"schema": {
					"$ref": "./schemas/associate-activity-logs-response-schema_v01.json"
				},
```

```js
/** @type { import('@redocly/cli').oasRule} */

const nextGenResponseModel = options => {
    const mustExist = options.mustExist || []
    
    return { 
        Response: { 
            skip: (_response, key) => {
                return ![200, 201, 202].includes(key.toString())
            },
            MediaType: { 
                skip: (_media, key) => {
                    return key !== 'application/json'
                },
                Schema(schema, { report, location }) { 
                    if (schema.type !== 'object') return

                    for (let element of mustExist) { 
                        if (!schema.properties[element]) {
                            report ({
                                message: `Next-Gen Response must have top-level "${element}"`,
                                location: location.child('properties')
                            })
                        }
                    }
                }
            }
        }
    }
}

module.exports = nextGenResponseModel
```

```yaml
    custom-id/nextGenResponseModel:
      description: Ensure the Response model follows the API Style Guide
      message:  {{ error }}
      severity: error
      mustExist:
        - _confirmMessage
        - _meta

  plugins: 
    -  './plugins/index.js'
```

**Comment by jeremyfiel** [comment]
i figured it out. my array of `[200, 201, 202]` needs to be in string format, not integer.  `['200', '201', '202']`

the linter successfully dereferences the file as expected.

```js
{
  schema: {
    '$schema': 'http://json-schema.org/draft-04/schema#',
    title: 'BenefitsActivityLogs',
    description: 'Benefits Activity Logs for a specific associate',
    type: 'object',
    properties: { benefitsAssociateActivityLogs: [Object], _confirmMessage: {} },
    additionalProperties: false
  }
}
```

```sh
...\v1\schemas\associate-activity-logs-response-schema_v01.json:
  6:16  error    custom-id/nextGenResponseModel  Next-Gen Response must have top-level "_meta"
```
please close.

**Comment by jeremyfiel** [comment]
I believe I've written the assertions syntax with the same conditions as the custom rule above but I'm not getting an error response.

can someone please guide me?  thanks,

```yaml
    assert/test-NG-response:
      subject: SchemaProperties
      context:
        - type: ResponsesMap
          matchParentKeys: ['200', '201', '202']
        - type: MediaTypeMap
          matchParentKeys: ['application/json']
      message: is my test working?
      severity: error
      mutuallyRequired:
        - _confirmMessage
        - _meta
 ```

**Comment by RomanHotsiy** [comment]
Should be `Response` and `MediaType` in the context.

That's how `matchParentKeys` works.

We need to add validation there or maybe rethink the naming.

**Comment by jeremyfiel** [comment]
Hey Roman.. not working either. 
no error is thrown for the assertion.  I have both rules defined so I would expect duplicate errors.  Is that a correct assumption?

```yaml
styleguide:
  extends:
    - recommended
  rules:
    info-license: off
    operation-operationId: off
    no-empty-servers: warn
    no-server-trailing-slash: off
    no-unused-components: off
    no-invalid-media-type-examples: off

    custom-id/nextGenResponseModel:
      description: Ensure the Response model follows the API Style Guide
      message:  {{ error }}
      severity: error
      mustExist:
        - _confirmMessage
        - _meta

    assert/test-NG-response:
      subject: SchemaProperties
      context:
        - type: Response
          matchParentKeys: ['200', '201', '202']
        - type: MediaType
          matchParentKeys: ['application/json']
      message: is my test working?
      severity: error
      mutuallyRequired:
        - _confirmMessage
        - _meta
  plugins: 
    -  './plugins/index.js'

 ```

```sh
$ redocly lint --config ~/repos/.redocly.yaml ./v1/associate-activity-management-swagger_v1.json --format=stylish

validating ./v1/associate-activity-management-swagger_v1.json...

\v1\schemas\associate-activity-logs-response-schema_v01.json:
  6:2  error    custom-id/nextGenResponseModel  Next-Gen Response must have top-level "_confirmMessage"
  6:2  error    custom-id/nextGenResponseModel  Next-Gen Response must have top-level "_meta"

\v1\schemas\associate-activity-log-details-response-schema_v01.json:
  6:2  error    custom-id/nextGenResponseModel  Next-Gen Response must have top-level "_confirmMessage"
  6:2  error    custom-id/nextGenResponseModel  Next-Gen Response must have top-level "_meta"

./v1/associate-activity-management-swagger_v1.json: validated in 64ms
```

**Comment by RomanHotsiy** [comment]
Sorry, I was replying from my phone. I'll check it when I get to laptop later.

**Comment by RomanHotsiy** [comment]
Just tested this locally, seems to work. I'll close the issue. Please, feel free to reopen.

```
assert/test-NG-response:
  subject: SchemaProperties
  context:
    - type: Response
      matchParentKeys: ['200', '201', '202']
    - type: MediaType
      matchParentKeys: ['application/json']
  message: is my test working?
  severity: error
  required:
    - _confirmMessage
    - _meta
```

**Comment by jeremyfiel** [comment]
@RomanHotsiy  it's not working on my side. 

```sh
$ redocly --version
1.0.0-beta.107
```

```yaml
styleguide:
  extends:
    - recommended
  rules:
    info-license: off
    operation-operationId: off
    no-empty-servers: warn
    no-server-trailing-slash: off
    no-unused-components: off
    no-invalid-media-type-examples: off

    # custom-id/nextGenResponseModel:
    #   description: Ensure the Response model follows the API Style Guide
    #   message:  {{ error }}
    #   severity: error
    #   mustExist:
    #     - _confirmMessage
    #     - _meta

    assert/test-NG-response:
      subject: SchemaProperties
      context:
        - type: Response
          matchParentKeys: ['200', '201', '202']
        - type: MediaType
          matchParentKeys: ['application/json']
      message: is my test working?
      severity: error
      mutuallyRequired:
        - _confirmMessage
        - _meta
  plugins: 
    -  './plugins/index.js'

```
```sh
$ redocly lint --config ~/repos/.redocly.yaml ./v1/associate-activity-management-swagger_v1.json --format=stylish
validating ./v1/associate-activity-management-swagger_v1.json...
./v1/associate-activity-management-swagger_v1.json: validated in 52ms

Woohoo! Your OpenAPI definition is valid. 🎉
```

my response schema is missing those two keys at the root level. 

```json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "ActivityLogs",
	"description": "Activity Logs for a specific associate",
	"type": "object",
	"properties": {
		"AssociateActivityLogs": {
			"type": "array",
			"items": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"activityLog": {
						"$ref": "../../../../common/logEntryBaseType_v02.json"
					},
					"links": {
						"type": "array",
						"items": {
							"$ref": "../../../../common/linkType_v01.json"
						}
					}
				}
			}
		}
	},
	"additionalProperties": false
}
```

if i use the commented out custom rule I wrote in JS, the errors are displayed as expected.

**Comment by RomanHotsiy** [comment]
@jeremyfiel 

Looks like you did not change `mutuallyRequired` to `required`:

```yaml
styleguide:
  extends:
    - recommended
  rules:
    info-license: off
    operation-operationId: off
    no-empty-servers: warn
    no-server-trailing-slash: off
    no-unused-components: off
    no-invalid-media-type-examples: off

    # custom-id/nextGenResponseModel:
    #   description: Ensure the Response model follows the API Style Guide
    #   message:  {{ error }}
    #   severity: error
    #   mustExist:
    #     - _confirmMessage
    #     - _meta

    assert/test-NG-response:
      subject: SchemaProperties
      context:
        - type: Response
          matchParentKeys: ['200', '201', '202']
        - type: MediaType
          matchParentKeys: ['application/json']
      message: is my test working?
      severity: error
      required:
        - _confirmMessage
        - _meta
  plugins: 
    -  './plugins/index.js'
```

**Comment by jeremyfiel** [comment]
ok, i see that now.  how can I get the conditions out of the assertion if I have more than one property required?  `message` only takes a string

**Comment by RomanHotsiy** [comment]
what do you mean? could you elaborate?

**Comment by jeremyfiel** [comment]
if i have a list of required properties, can I expect the error to output which property was not found? 

`message: "_confirmMessage" was not found`

**Comment by adamaltman** [comment]
Side note: we have a built in rule: https://redocly.com/docs/cli/rules/response-contains-property/

Having template placeholders to available to use in messages would be good.

**Comment by RomanHotsiy** [comment]
Yes, we'll open a ticket for adding placeholders 👍 

@jeremyfiel would you be open to jump on a short call to discuss assertions syntax later this week?

We're working on finalizing the syntax before `v1.0.0` release and would like to hear some of your feedback.

**Comment by jeremyfiel** [comment]
> 

i'm using this one and I like the names idea but I also need a way to have a `not` for edge cases rather than the existing assumption that 204 no content is sufficient for all operations.  maybe the naming could be similar to the rules engine predicate and use `skip`

```js
export const ResponseContainsProperty: Oas3Rule = (options) => {
  const names: Record<string, string[]> = options.names || {};
  let key: string | number;
  return {
    Operation: {
      Response: {
        skip: (_response, key) => {
          return `${key}` === '204';
```

I'm not sure my syntax makes total sense, but I hope you get the idea.  the `not` should be relative to the `subject` which I'm guessing is your naming convention.. `response... == Operation > Response`

e.g. 
```yaml
response-contains-property:
      severity: error
      names:
        '200':
          - _confirmMessage
          - _meta
          not|skip:
            - delete
        '201':
          - _confirmMessage
        '202':
          - _confirmMessage
        '400':
          - _confirmMessage
        '403':
          - _confirmMessage
        '404':
          - _confirmMessage
        '500': 
          - _confirmMessage
        '503':
          - _confirmMessage
```

my scenario is we typically $ref the `_confirmMessage` schema alongside other root nodes in response payloads how I described in my previous messages. But, I also have some scenarios where we $ref the `_confirmMessage` schema directly rather than as a sub-schema. This built-in rule is throwing an error for that scenario where I don't need to report it because my `_confirmMessage` schema doesn't contain the `_meta` schema. 

```sh
specs\common\shared\confirm-message-schema_v03.json:
  6:2  error    response-contains-property  Response object must contain a top-level "_meta" property.
```
