### ISSUE TITLE
Bundler adding extra complication to externally referenced schemas

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/redocly-cli#818]
**Describe the bug**
This is a variation of issue #349 that you fixed for me several months ago. 

If you have something like this in components.schemas:

```
components:
  schemas:
    myObject:
      $ref: ../path/to/myObject.v2.schema.yaml
```

The bundler output will look something like this:

```
components:
  schemas:
    myObject:
      $ref: '#/components/schemas/myObject.v2.schema'
    myOjbect.v2.schema:
      title: some object
      type: object
      description: This is the example object
      properties:
        key:
          type: string
          description: UUID
          readOnly: true
          .
          .
          .
```

While the extra schema is in some ways invisible (that is, using myObject still ultimately gets to the right schema), adding the schema that has a name based on the file name is completely unnecessary. It would be kind of embarrassing to give this OpenAPI definition to someone who wants to build a client for my service because they'd ask about the unneeded indirection.

**Expected behavior**

I would expect the output to look like this:

```
components:
  schemas:
    myObject:
      title: some object
      type: object
      description: This is the example object
      properties:
        key:
          type: string
          description: UUID
          readOnly: true
          .
          .
          .
```

There is no need to create a new schema; just replace the $ref line with the contents from the referenced file. 

**OpenAPI definition**
OAS v3.0

**Redocly Version(s)**
$ redocly --version
1.0.0-beta.102

**`Node.js` Version(s)**
v18.7.0
