### ISSUE TITLE
Values ending in space or newline get odd treatment by bundle and join

### ISSUE THREAD

**Issue by steve-nay-sage** [Redocly/redocly-cli#834]
**Describe the bug**
I have some multiline descriptions in my OpenAPI schemas. Here's an example of a tag description:

```
tags:
  - name: Contacts
    description: |
      You can think of contacts as a common, shared address book that's used across a company by many people for a variety of purposes. Contacts hold all the information needed to contact an individual or business, including name, email address, phone number, mailing address, and more. 
      
      Contacts are almost always used with other Sage Intacct objects, such as vendors, customers, or locations. For example, you specify a contact in Order Entry and Purchasing transactions to set a ship-to, bill-to, pay-to, or return-to addresses, and to determine tax on transactions.

servers:
  - url: 'http://localhost:3000'
```

Notice the empty line at the end of the description. That--or if the last character is a space instead of new line--results in strange output from the bundle and join operations. Here is the result after bundle:

```
tags:
  - name: Contacts
    description: "You can think of contacts as a common, shared address book that's used\nacross a company by many people for a variety of purposes. Contacts hold\nall the information needed to contact an individual or business, including\nname, email address, phone number, mailing address, and more. \n\n\nContacts are almost always used with other Sage Intacct objects, such as\nvendors, customers, or locations. For example, you specify a contact in\nOrder Entry and Purchasing transactions to set a ship-to, bill-to, pay-to,\nor return-to addresses, and to determine tax on transactions.\n"
servers:
  - url: http://localhost:3000
```

Notice that it's no longer a multi-line text field, is wrapped in quotes, and \n has been inserted where it thinks there need to be line breaks (which may be based on a max line length setting?) .

In one sense this is just an aesthetic issue, as the display of the field looks the same in Redocly. But it looks pretty odd when I go in and look at the file after bundling. I'd call it a minor bug.

**To Reproduce**
1. Create an OpenAPI file with a multi-line description field. Put a space or a newline at the end of the field.
2. Run `redocly bundle` on the file. I think `redocly merge` does the same thing, but you need multiple files to test that.
3. Look at the description field in the bundled file.

**Expected behavior**
The description field should still be a multi-line text field, without inserted newlines. It's fine to trim any extra white space off the end.

**Redocly Version(s)**
1.0.0-beta.102

**`Node.js` Version(s)**
v18.7.0
