### ISSUE TITLE
New decorator to remove specific property

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [Redocly/redocly-cli#867]
**Is your feature request related to a problem? Please describe.**

This is a feature request. I would like a filter to remove a property. The current decorators remove entire nodes, but I only want a property of the node removed. For example 

```
properties:
  property1:
    type: boolean
    description: This is a description
    example: false
    x-source: This contains internal data about how we get and use the data
  property2:
    type: string
    format: date
    description: This is a description
    example: '2021-04-22'
    x-source: This contains internal data about how we get and use the data
  property3:
    type: number
    format: float
    description: This is a description
    example: 0
    x-source: This contains internal data about how we get and use the data
```
We want to only remove x-source, not the entire node.

**Describe the solution you'd like**

The ability to remove just a property while leaving the node intact.

**Describe alternatives you've considered**

We have tried the built in decorators filter-out and remove-x-internal but they both remove the entire node.

**Additional context**

I wrote a custom plugin based on remove-x-internal, but I am sure it could be done better.
```
/** @type {import('@redocly/openapi-cli').OasDecorator} */
function RemoveInternalSchemaProperties() {
  return {
    SchemaProperties: {
      leave(properties) {
        Object.keys(properties).forEach((propertyName) => {
          if (properties[propertyName]['x-source']) {
            delete properties[propertyName]['x-source'];
          }
        });
      },
    },
  };
}

module.exports = RemoveInternalSchemaProperties;
```
