### ISSUE TITLE
Between beta 108 and 111 styleguide was removed

### ISSUE THREAD

**Issue by michaelgwelch** [Redocly/redocly-cli#911]
**Describe the bug**

Between beta 108 and beta 111 the styleguide keyword was removed. I now get a warning like this:

```bash
The 'styleguide' field is deprecated. Read more about this change: https://redocly.com/docs/api-registry/guides/migration-guide-config-file/#changed-properties
```

I want to resolve this, but the information at the given link doesn't seem to have been updated with this specific change. (I don't see `styleguide` anywhere on that page).

**Redocly Version(s)**

In the process of upgrading from `@redocly/cli@1.0.0-beta.108` to `@redocly/cli@1.0.0-beta.111` but before we complete the upgrade I'd like to resolve the warning.

**`Node.js` Version(s)**

**Additional context**

We are currently using `styleguide` for the following:

```yaml
styleguide:
  plugins:
    # custom plugin
    - './redocly-plugins/jci-plugins.js'

  extends:
    - recommended
    - jci-plugins/private

  rules:
    paths-kebab-case: off
    boolean-parameter-prefixes: off
    tags-alphabetical: off
    info-contact: off
    info-license: off
    operation-4xx-response: off
    no-invalid-media-type-examples: error
    parameter-description: error
    operation-description: error
    operation-tag-defined: error
```
