### ISSUE TITLE
assertions: assertions only return first error instance

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#915]
in relation to the reusable header shortcoming by the OAS spec, https://github.com/Redocly/redocly-cli/issues/611

we have adopted a naming scheme to use a prefix in front of named parameters.
`header_` `query_` `path_`

I tried to use assertions to validate parameter naming but I have an issue with the assertions error reporting.
- the assertion only flags the first instance, this is very misleading because if you fix the first one, the error persists for another instance of the same assertion. 

these two examples will fail `camelCase` assertion because of the prefix but only the first one is reported

```sh
437:4  warning  named-parameters-camelCase assertion  Parameters must use camelCase
```
```json
                       "header_roleCode": {
				"description": "The role the user is playing during the transaction",
				"name": "roleCode",
				"in": "header",
				"required": true,
				"schema": {
					"$ref": "../../../common/security/userRoleType_v01.json"
				}
			},
			"header_Accept": {
				"name": "Accept",
				"in": "header",
				"description": "Accept' ': ' ( '*/*' | (type'/' '*') | (type'/'subtype)) ['; ' 'q' '='qvalue]. Describes media type(s) and subtype(s) that are acceptable for the response. The optional qvalue represents an acceptable quality level for acceptable types.",
				"required": false,
				"schema": {
					"type": "string"
				}
			}
```
**Expected Behavior**

The tool should output the complete list of assertion errors otherwise I could spend hours or days running the tool over and over and having a new error thrown for the same assertion rule.

**Reproducible Example**

```json
{
    "openapi": "3.0.3",
    "info": {
        "title": "",
        "description": "adfds",
        "version": "",
        "contact": {
            "name": "jeremy",
            "email": "jeremy@me.com"
        },
        "license": {"name": "MIT", "url": "example.com"}
    },
    "tags": [
        {
            "name": "sometag",
            "description": "adfd"
        }
],
"servers": [
    {
        "url": "https://jeremy.com"
    }
],
"security": [],
"paths": {
    "/output/{output-id}/getObject": {
        "get": {
            "tags": [
                "sometag"
            ],
            "operationId": "adfs",
            "description": "dfdsf",
            "summary": "this is a summary",
            "parameters": [
                {
                    "name": "output-id",
                    "in": "path",
                    "required": true,
                    "schema": {
                        "type": "string"
                    }
                },
                {
                    "$ref": "#/components/parameters/header_Accept"
                }
            ],
            "responses": {
                "200": {
                    "description": ""
                },
                "400": {
                    "description": ""
                }
            }
        }
    }
},
"components": {
    "parameters": {
        "header_roleCode": {
            "description": "The role the user is playing during the transaction",
            "name": "roleCode",
            "in": "header",
            "required": true,
            "schema": {
                "type": "string"
            }
        },
        "header_Accept": {
            "name": "Accept",
            "in": "header",
            "description": "Accept' ': ' ( '*/*' | (type'/' '*') | (type'/'subtype)) ['; ' 'q' '='qvalue]. Describes media type(s) and subtype(s) that are acceptable for the response. The optional qvalue represents an acceptable quality level for acceptable types.",
            "required": false,
            "schema": {
                "type": "string"
            }
        }
    }
}
}
```
```yaml
styleguide:
  extends:
    - recommended
  rules:
    info-license: off
    security-defined: off
    
    operation-operationId: off
    operation-description: error
    operation-summary: warn
    operation-tag-defined: warn
    operation-singular-tag: warn

    no-empty-servers: warn
    no-server-trailing-slash: off
    no-unused-components: off
    no-invalid-media-type-examples: off
      # severity: warn
      # allowAdditionalProperties: false
    paths-kebab-case: warn
    no-http-verbs-in-paths:
      severity: warn
      splitIntoWords: true

    assert/named-parameters-camelCase:
      subject: NamedParameters
      message: Parameters must use camelCase
      severity: warn
      casing: camelCase
```

```sh
1.0.0-beta.111
```

**Comment by SmoliyY** [comment]
@jeremyfiel This should be fixed in the `beta-112` release. By the way new assertion rule now looks like this: 

```yaml
assert/named-parameters-camelCase:
      subject:
        type: NamedParameters
      message: Parameters must use camelCase
      severity: warn
      assertions:
        casing: camelCase
```
Please take a look at the new assertions [docs](https://github.com/Redocly/redocly-cli/blob/main/docs/rules/custom-rules.md).
