### ISSUE TITLE
assertions: allow optional prefix for key (SchemaProperties, Named...)

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#916]
we have adopted a naming scheme to use a prefix in front of named parameters and/or schema properties.
NamedParameters; `header_` `query_ ` `path_`
SchemaProperties: `_` or  `/` or `$`

Is it possible to have an optional prefix in the assertion syntax for `casing` to allow such naming schemes?

**Describe the solution you'd like**
i would like the assertion syntax to take an array of `prefix` properties: 
```yaml
    assert/named-parameters-snake_case:
      subject: NamedParameters
      message: Parameters must use snake_case
      severity: warn
      casing: snake_case
          prefix:
              - header_
              - query_
              - path_
              - _
              - /
              - $
```

I saw an example of this with the `response-contains-property` built-in rule example where you used `names` in a custom rule

**Describe alternatives you've considered**
creating a custom rule

**Comment by tatomyr** [comment]
Hi @jeremyfiel,

Will a regex pattern cover your needs? Perhaps something like this: 

```yaml
 assert/named-parameters-snake_case:
      subject: NamedParameters
      message: Parameters must use snake_case
      severity: warn
      pattern: ^(header_|query_|path_|_|\/_|$)([a-z][a-z0-9]*)(_[a-z0-9]+)*$
       
```
