### ISSUE TITLE
nullable in schema object must have a type sibling

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#925]
**Describe the bug**

From 3.0 about `nullable`:

> A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object. Other Schema Object constraints retain their defined behavior, and therefore may disallow the use of null as a value. A false value leaves the specified or default type unmodified. The default value is false.

**To Reproduce**

This schema should not be valid because `foo` definition has `nullable` and that does not have an explicit sibling of `type`. 

```yaml
schema:
  type: object
  properties:
    foo:
       nullable: true
```

People also seem to think this is valid, but it isn't:

```yaml
schema:
  type: object
  properties:
    foo:
       nullable: true
       allOf:
          $ref: # some reference
```

**Expected behavior**

Let the user know where incorrect use of `nullable` has happened.

**Logs**

N/A

**OpenAPI definition**

OpenAPI 3.0.

**Redocly Version(s)**

1.0.0-beta.112

**`Node.js` Version(s)**

16

**Additional context**

n/a
