### ISSUE TITLE
routingBasePath not working on "redocly preview-docs"

### ISSUE THREAD

**Issue by h4mit** [Redocly/redocly-cli#926]
I added a redocly preview-docs in .redocly.yaml, but not working and don't change base path. Start preview server  with  ```/``` path.

my   .redocly.yaml is:
```
# See https://redocly.com/docs/cli/configuration/ for more information.
apis:
  sample@v1:
    root: api-docs/openapi/openapi.yaml
extends:
  - recommended
rules:
  no-unused-components: error
features.openapi:
  routingBasePath: "/vdoc"
  htmlTemplate: ./api-docs/docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages: # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl
      - lang: Node.js
      - lang: JavaScript
      - lang: PHP
      - lang: Python

```

**Redocly Version(s)**
```"@redocly/cli": "^1.0.0-beta.111"```

**`Node.js` Version(s)**
```16```
