### ISSUE TITLE
custom rules: Schema property names endsWith, invalid property reported

### ISSUE THREAD

**Issue by jeremyfiel** [Redocly/redocly-cli#936]
**Describe the bug**
I'm not sure if this is a bug or not but it appears to be.

I'm building a custom rule to validate plural property names are using `type: array` declaration.

initially, I'm just trying to get the schemas and checking if the property name ends in a basic check of 's' 'es' or 'ies'.  then, check if the type definition is correct.

```js
const collectionFieldNamingRules = (options) => {
    const suffix = options.suffix || [];

    return {
        Schema(_schema, { report, key }) {
            for (let element of suffix) {
                if (key.toString().endsWith(element) && !key.toString().endsWith("us") && _schema.type !== 'array') {
                    report({
                        message: `Use of plural properties (${key}) does not have the proper type definition "type": "array"`,
                        location: key
                    })
                }
            }
        },
    }
};

module.exports = collectionFieldNamingRules
```

```yaml
  myrules/collectionFieldNamingRules:
    description: 'Ensure a property representing a collection ends in a plural and defines the correct type definition "type": "array"'
    message:  {{ error }}
    severity: error
    suffix:
      - s
      - ies
      - es
```

The issue I'm having is the tool seems to be reaching into the Schema properties and finding the `items` keyword of an array definition.  

```sh
specs\common\linkType_v01.json:
  1:1     error    myrules/collectionFieldNamingRules  Use of plural properties (items) does not have the proper type definition "type": "array"
```

```json
"links": {
      "type": "array",
      "items": {
	      "$ref": "../../../../common/linkType_v01.json"
}
```

**Expected behavior**
I don't think the `items` keyword should be reported here. 

Otherwise, I think it seems to be working on a few tests I did. 
```sh
specs\common\commentBaseType_v02.json:
  1:1  error    myrules/collectionFieldNamingRules  Use of plural properties (comments) does not have the proper type definition "type": "array"
```

```json
"comments": {
	"description": "Notes or comments that may be provided by a third-party, ",
	"$ref": "../../../../../common/commentBaseType_v02.json"
		}
```

**Redocly Version(s)**
1.0.0-beta.112

**`Node.js` Version(s)**
v16.14.0
