### ISSUE TITLE
Remove unused components in config

### ISSUE THREAD

**Issue by adamaltman** [Redocly/redocly-cli#945]
**Is your feature request related to a problem? Please describe.**

There is no way to designate that an API should be bundled with the remove-unused-components flag. This means the config alone is unreliable and can result in bundling with unused components even if the designer's intention is to force it to always bundle without unused components.

**Describe the solution you'd like**

I would like a way to designate that remove-unused-components should be used.

Something like this. I understand it needs to run last.

```yaml
apis:
  core@latest:
    root: openapi/openapi.yaml
    decorators:
      filter-in:
        property: x-products
        value:
          - Core
      remove-unused-components: on
```
**Describe alternatives you've considered**

```yaml
apis:
  core@latest:
    root: openapi/openapi.yaml
    remove-unused-components: true
    decorators:
      filter-in:
        property: x-products
        value:
          - Core
```

I'm good with either.

**Additional context**

Happy to answer any questions.
