### ISSUE TITLE
Add support for any type in assertions

### ISSUE THREAD

**Issue by RomanHotsiy** [Redocly/redocly-cli#946]
**Is your feature request related to a problem? Please describe.**
It's complicated to target common field across multiple types with assertions. This is especially cumbersome when you want to create a custom rule for `description` fields across many types.

**Describe the solution you'd like**
Implement a new type `any` so we can do something like:

```yaml
subject:
  type: any
  property: description
assertions:
  notPattern: /(was|will)/ 
```

**Describe alternatives you've considered**
Support for an array in `type`.

**Additional context**
In fact this may be working. If it does, we need to test it, cover it with tests and document.
