### ISSUE TITLE
Lint rule spec-components-invalid-map-name not applied for all examples

### ISSUE THREAD

**Issue by austpaul** [Redocly/redocly-cli#959]
**Describe the bug**
The `spec-components-invalid-map-name` rule seems to not being applied for components having examples with invalid map names if the component is being referred to within the spec. Only examples for unused types are validated.

**To Reproduce**
1. Given the following `redocly.yaml` config
```
lint:
  extends:
    - recommended
  rules:
    no-unused-components:
      severity: off
```
2. And the attached OpenAPI (compressed)
3. Run this command with these arguments... `redocly lint bikes_v2.yaml`
```
The map key in examples "a param example" does not match the regular expression "^[a-zA-Z0-9\.\-_]+$"
The map key in examples "a response example" does not match the regular expression "^[a-zA-Z0-9\.\-_]+$"
Validation failed with 2 errors.
```

**Expected behavior**
4 errors, one for each instance of an invalid example map name instead of only errors for examples for the two unused components.

**OpenAPI definition**
[bikes_v2.yaml.zip](https://github.com/Redocly/redocly-cli/files/10186231/bikes_v2.yaml.zip)

**Redocly Version(s)**
1.0.0-beta.112

**`Node.js` Version(s)**
v18.2.0

**Comment by adamaltman** [comment]
I reproduced this on 1.0.0-beta.117

With this config:

```yaml
apis: 
  bikes:
    root: ./bikes_v2.yaml
extends:
  - recommended
rules:
  no-unused-components: off
```

**Comment by IgorKarpiuk** [comment]
Hi @austpaul,  we have changed  behavior for `spec-components-invalid-map-name`  rule, now we only validate top-level keys. see details here: https://github.com/Redocly/redocly-cli/issues/1104

if you need validate nested keys, you can use assertions like this:

```yaml
rule/no-space-in-example-keys:
    subject: 
      type: ExamplesMap
    assertions: 
      pattern: /^[a-zA-Z0-9\.\-_]+$/
```
