### ISSUE TITLE
Add the possibility of using in-built decorators multiple times

### ISSUE THREAD

**Issue by romanpryshliak** [Redocly/redocly-cli#970]
**Is your feature request related to a problem? Please describe.**

Currently, it is impossible to use the same in-built decorator more than once in the `redocly.yaml` configuration file.

**Describe the solution you'd like.**

```
decorators:
  filter-out:
    - property: x-audience
      value: internal
      matchStrategy: any
    - property: x-test
      value: true
      matchStrategy: any
```

**Additional context.**

https://app.frontapp.com/open/cnv_uqgtia4
